### ISSUE TITLE
Stone brick doesn't allow you to select productivity modules

### ISSUE THREAD

**Issue by SteveS8** [factoriolab/factorio-lab#104]
Stone brick for some reason only shows speed modules in the furnaces

**Comment by dcbroad3** [comment]
Good catch. It looks like it's because the stone brick is listed under logistics instead of intermediate products.

**Comment by hhrhhr** [comment]
The _stone block_ should be in the _logistics_ section. Productivity modules can only be applied to predefined products:
```
    ["productivity-module"] = {
      type = "module",
      name = "productivity-module",
--
      subgroup = "module",
      category = "productivity",
--
      limitation = {
--
        "steel-plate",
        "stone-brick", -- <--!
        "sulfur",
--```
