### ISSUE TITLE
bug in settings UI

### ISSUE THREAD

**Issue by hhrhhr** [factoriolab/factorio-lab#105]
url: http://localhost:4200/list#eJwrsDU0MbMytjI20DE0MQUz1IptrQytrKxMrMzNgJShgaWVARgCAZAAAByPCv8=

Reduce the browser window vertically until a scroll slider appears, open settings, scroll down:
![Opera Снимок_2020-06-03_161322_localhost](https://user-images.githubusercontent.com/966048/83640780-498f1980-a5b5-11ea-9efc-cea89e43cc6d.png)

**Comment by bbarry** [comment]
In Firefox and Chrome:
![image](https://user-images.githubusercontent.com/84951/83643151-aec71880-a57d-11ea-9ca6-ddc1e756529b.png)

![image](https://user-images.githubusercontent.com/84951/83642912-6a3b7d00-a57d-11ea-9bfc-aced9c2b3eb6.png)

It does look like the z indexes are off for a few things.

Where are your module icons coming from?

**Comment by SteveS8** [comment]
It actually would be pretty cool to have the settings menu always visible on the left no matter how far you scroll down. But obviously not like this

**Comment by dcbroad3** [comment]
Those elements have to be absolutely positioned in order to allow the dropdowns float outside of the settings panel. I have them set to handle vertical scroll inside the settings panel but this is related to scrolling the whole body of the page. I should be able to address this.
