### ISSUE TITLE
use ingame ids

### ISSUE THREAD

**Issue by hhrhhr** [factoriolab/factorio-lab#112]
In order to avoid confusion, I would recommend using in-game product IDs everywhere.

`logistic-chest-active-provider` -> `active-provider-chest` (and all other chests)
`small-lamp` -> `lamp`
`stone-wall` -> `wall`
`solar-panel-equipment` -> `portable-solar-panel`
`fusion-reactor-equipment` -> `portable-fusion-reactor` (and all other equipment)
category (name of recipe group) `intermediate-products` -> `intermediate`

**Comment by dcbroad3** [comment]
Agreed. I started on this in the Rationals branch I think, but this should be finished out. I originally got the ids I use from the Factorio wiki, I'm not sure why they are different there.
