### ISSUE TITLE
How to change default settings?

### ISSUE THREAD

**Issue by hhrhhr** [factoriolab/factorio-lab#116]
I mean the default factory/furnace/..., item/belt/... precison, used modules.
Maybe, by analogy with the well-known calculator, add something like settings.js at least for local use?

**Comment by dcbroad3** [comment]
I think I might need some clarification on this. Are you referring to something the settings menu can't do? This should be doable by using the settings menu and then saving the url; the bookmark would contain the settings. Do you mean the default settings when you first open the page without modifying anything? Those are set [here](https://github.com/factoriolab/factorio-lab/blob/7143b16bdd852993a75240a547588a9f135fee43/src/app/store/settings/settings.reducer.ts#L38)

**Comment by hhrhhr** [comment]
> Those are set [here](https://github.com/factoriolab/factorio-lab/blob/7143b16bdd852993a75240a547588a9f135fee43/src/app/store/settings/settings.reducer.ts#L38)

Yes, this is what I need, thanks.

**Comment by dcbroad3** [comment]
@hhrhhr Can this be closed, does that file address your issue?
