### ISSUE TITLE
Setting factory count doesn't work for petroleum

### ISSUE THREAD

**Issue by SteveS8** [factoriolab/factorio-lab#117]
Changing the number of factories doesn't do anything for petroleum, HO or LO. It does for acid and lubricant. Granted, Factorio Calculator is screwy there too. It takes some kind of weird total amount (including cracking), but trial and error lets you get it to an even amount of refineries. 

With this changing the factories doesn't change anything at all. Maybe "factories" should be the number of refineries and the number of crackers is adjusted automatically to consume all left overs

**Comment by dcbroad3** [comment]
I don't think I understand. Can you send me a link where the factories don't work? [Here](https://factoriolab.github.io/list#eJwrsDU0MLYytjIEAAt9Aho=) is a link showing 1 factory of petroleum gas production, it's the total output from one refinery. All the oil products go by number of refineries. 

Unfortunately I am working on a more generic, mod-friendly way to handle this and the factory option for oil products will likely be disabled when that is completed.

**Comment by SteveS8** [comment]
It works for one factory. Now enter "2" as the factory number. Nothing changes for me. As said, I realize that there are are some issues with this in general. Like deciding what number you are actually adjusting. But not doing anything kind of makes it useless.

I generally adjust the number until I have the number of refineries I want to see how much cracking I need.

**Comment by dcbroad3** [comment]
That's interesting, I must have forgotten to multiply by the rate. I still think most likely this will be disabled for items with no simple recipe in a version soon, because with mods I don't see how it could work.

**Comment by dcbroad3** [comment]
Sure enough, the issue is obvious [here](https://github.com/factoriolab/factorio-lab/blob/7143b16bdd852993a75240a547588a9f135fee43/src/app/store/products/products.selectors.ts#L179), I forgot to multiply by the rate.
