### ISSUE TITLE
Changing number of beacons on oil refinery fails

### ISSUE THREAD

**Issue by keeshoekzema** [factoriolab/factorio-lab#123]
For example, on this url: https://factoriolab.github.io/list#eJx1isEKhDAMRP/G0wZK1UugH1NqkLDahDQK+/dbhb25M5fhvdG0c+W6gposR3E+2T8YMM5hsFRElQzECBGbEi2w99tGMOKLTeof1VzqEy+StwdsUt7koNm8W5zC0BLOd3+J08X7+AKPGDpD

If i want to change the number of beacons on the oil refinery from 24 to 32 i get this error in the console:
ERROR TypeError: "this.recipeSettings[this.steps.find(...).itemId] is undefined"
    beaconCountChange https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    Ay https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    Ws https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    r https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    st https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    invokeTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    onInvokeTask https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    invokeTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    runTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    invokeTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    p https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    f https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
main-es2015.3884152e248a9d86f322.js:1:81352
    mn https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    handleError https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    xr https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    Ws https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    r https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    st https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    invokeTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    onInvokeTask https://factoriolab.github.io/main-es2015.3884152e248a9d86f322.js:1
    invokeTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    runTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    invokeTask https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    p https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1
    f https://factoriolab.github.io/polyfills-es2015.690002c25ea8557bb4b0.js:1

**Comment by dcbroad3** [comment]
Thanks for the report, I'll look into this ASAP.

**Comment by dcbroad3** [comment]
@keeshoekzema This should be resolved, let me know if you still see any issues with it.
