### ISSUE TITLE
Heavy oil cracking

### ISSUE THREAD

**Issue by IshFx** [factoriolab/factorio-lab#142]
Hello,

I found that the calculator doesn't automatically crack heavy oil into light oil (it still cracks light into petroleum gas).
I remember that it used to do it before.

Is this the intended way, or is it a bug ?

Here is an example : 
[https://factoriolab.github.io/list#p=petroleum-gas:1:2](https://factoriolab.github.io/list#p=petroleum-gas:1:2)

![image](https://user-images.githubusercontent.com/23222270/90333523-d6e3e680-dfc6-11ea-81c0-30c759579756.png)

As you can see, we're left with 6648 heavy oil.

Thanks in advance!

**Comment by dcbroad3** [comment]
That very much sounds like a bug. I'll look into it ASAP, thanks for the report!

**Comment by dcbroad3** [comment]
Looks like a change I make to get Krastorio 2 to work caused it to consider water more expensive, and it avoids heavy oil cracking to reduce water consumption. Not a straightforward bug but definitely needs to be fixed.

**Comment by IshFx** [comment]
Alright, thanks for the quick response !
