### ISSUE TITLE
Factorio Extended Plus

### ISSUE THREAD

**Issue by Majere119** [factoriolab/factorio-lab#190]
**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factorio-lab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.

**What mod set are you requesting?**
FactorioExtended-Plus (https://mods.factorio.com/mod/FactorioExtended-Plus-Core)

**Is this mod set compatible with the latest version of Factorio?"
Yes, 1.0

**What mods are included in this mod set?**
https://mods.factorio.com/mod/FactorioExtended-Plus-Core
https://mods.factorio.com/mod/FactorioExtended-Plus-Transport
https://mods.factorio.com/mod/FactorioExtended-Plus-Machines
https://mods.factorio.com/mod/FactorioExtended-Plus-Power
https://mods.factorio.com/mod/FactorioExtended-Plus-Equipment
https://mods.factorio.com/mod/FactorioExtended-Plus-Logistics
https://mods.factorio.com/mod/FactorioExtended-Plus-Weaponry
https://mods.factorio.com/mod/FactorioExtended-Plus-Storage

I think only Core, Transport, and Machines packages should be necessary for spm calculations

**Comment by dcbroad3** [comment]
Thanks for the suggestion! I'll look into this the next chance I get.

**Comment by Majere119** [comment]
Thank you! This'll help me get back on track for my 18k base!

**Comment by sstrang** [comment]
Is there any chance that this could be updated to include the additional modules and beacons too? https://mods.factorio.com/mod/FactorioExtended-Plus-Module
