### ISSUE TITLE
Heavy oil cracking (again)

### ISSUE THREAD

**Issue by IshFx** [factoriolab/factorio-lab#219]
Hey, 

It seems that this bug https://github.com/factoriolab/factorio-lab/issues/142 is back again.
The steps to reproduce it are the same.

Thanks in advance!

**Comment by dcbroad3** [comment]
Thanks for reporting this, I'll make sure to add a regression test specifically for this issue this time. 
The linear program solver was completely overhauled a couple days ago and I somehow missed this in my testing.

**Comment by dcbroad3** [comment]
@IshFx For what it's worth, this was not so much a regression as it was a _completely_ different issue that happened to have the same end result. 🙃 Nonetheless, I wrote an extra unit test that checks specifically for this issue. Thanks again for the report!

**Comment by IshFx** [comment]
Oh ! Glad this was fixed then :smile: 
Thanks for this great calculator.
