### ISSUE TITLE
Odd focus behavior when clicking the up arrow to set output rate

### ISSUE THREAD

**Issue by terhuneb** [factoriolab/factorio-lab#233]
When clicking the up arrow to set output rate, the focus shifts back to the down arrow despite the mouse pointer not moving. Clicking again without moving the mouse will click the down arrow. Moving the mouse slightly will regain focus on the up arrow so it can be clicked.

**Comment by dcbroad3** [comment]
I've had others bring up this issue as well. Those buttons are built directly by the browser, and so I don't think I have very much control over them, but I do need to look into this to see if there's some way I can resolve it.
