### ISSUE TITLE
Autogenerated Factory Blueprint

### ISSUE THREAD

**Issue by RexBelli** [factoriolab/factorio-lab#239]
**Is your feature request related to a problem? Please describe.**
Have you considered using a [routing algorithm](https://en.wikipedia.org/wiki/Routing_(electronic_design_automation)) to auto generate factory blueprints?  I'm not sure it's even possible, but once you have the inputs and outputs of all the factory components, the work to lay that all out feels very similar to printed circuit board design.

**Describe the solution you'd like**
It would be really neat to plan out the entire factory in this planner and then have it auto generate a blueprint to put down in game.

**Describe alternatives you've considered**
The alternative is to design and lay it out yourself (e.g. play the game!).

**Comment by dcbroad3** [comment]
That's a very interesting suggestion, but feels like a completely different application than what the calculator is today. There are a lot of variables... how do you calculate how much beacons should overlap, how do you properly determine when a layout is or is not possible (high number of beacons isn't always possible, super high throughput assemblers sometimes don't have enough space around them for all the inserters required). Does the user want to use belts, bots, car-belts, trains...

All in all the tool you're describing isn't really feasible inside the HTML/JavaScript environment of this calculator anyway. You'd need to be running that inside Lua, really, leveraging the Factorio engine itself. It's a great idea for a separate tool, although it sounds extremely difficult to make. Theoretically a mod could let you plug in requirements from this calculator in some format and generate a blueprint for you, but I don't think this is possible in the environment of the calculator itself.

I'm going to close this issue as this is outside the scope of anything I think will ever be possible for this calculator, but I appreciate the suggestion!

**Comment by RexBelli** [comment]
Makes sense!  Thank you for your thoughts on the matter!
