### ISSUE TITLE
Incorrect recipe

### ISSUE THREAD

**Issue by jesper2k** [factoriolab/factorio-lab#256]
**Describe the bug**
The recipe result for green, red and blue circuits in the Expensive set of Krastorio 2 don't match up with the ingame recipes.

The ingame recipes yield 1 circuit
The calculator recipes yield 2 circuits

**To Reproduce**
In the calculator: Set the recipe base to Krastorio 2 and calculate resources for a blue circuit
Toggle expensive mode on, and there's no change, while there is ingame

**Expected behavior**
The calculator recipes should yield 1 ciurcit for the three (and potentially more) recipes

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.111 (I think... , I just googled current chrome version)

**Additional context**
I'm not entirely sure if this is caused by any recent updates, but I haven't updated my mods in a while, and a recipe change like this is quite unlikely.

**Comment by dcbroad3** [comment]
So this is the JSON for the electronic circuit in Krastorio 2:
```json
    {
      "expensive": {
        "in": {
          "copper-cable": 4,
          "iron-plate": 1,
          "wood": 1
        }
      },
      "id": "electronic-circuit",
      "in": {
        "copper-cable": 4,
        "iron-plate": 1,
        "wood": 1
      },
      "out": {
        "electronic-circuit": 2
      },
      "producers": [
        "assembling-machine-1",
        "assembling-machine-2",
        "assembling-machine-3",
        "kr-advanced-assembling-machine"
      ],
      "time": 2
    },
```

Currently, the code takes every entry in the "expensive" list and overwrites the default. But it looks like the actual in-game behavior is different, it overwrites the "out" field regardless. In other words, my code doesn't overwrite the default "out" values for the expensive mode recipe to set it back to 1, but the game actually does. 

This shouldn't be too difficult to fix, and fortunately the JSON itself is OK.

**Comment by dcbroad3** [comment]
Nope, I'm wrong, explosives in the base game outputs 2 items in both normal and expensive mode without re-declaring it in the expensive block. Still investigating.
