### ISSUE TITLE
FactorioExtended Plus Module

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#258]
Request to add FactorioExtended-Plus-Module to the existing FactorioExtended Plus recipe set.
https://mods.factorio.com/mod/FactorioExtended-Plus-Module

https://github.com/factoriolab/factorio-lab/issues/190#issuecomment-716644457

**Comment by dcbroad3** [comment]
@sstrang Adding your request as a new issue.

**Comment by sstrang** [comment]
Thanks!
