### ISSUE TITLE
Krastorio 2 problems

### ISSUE THREAD

**Issue by LunaticChicken** [factoriolab/factorio-lab#265]
1. Sand recipe using crushers is not correct. It should be 7.5 times cheaper
![Screenshot_1](https://user-images.githubusercontent.com/54511054/98007709-c04e6e00-1e04-11eb-9922-dae2d889ba44.png)

2. There is no default recipe for raw rare metals using mining drills
![Screenshot_4](https://user-images.githubusercontent.com/54511054/98008265-67330a00-1e05-11eb-8195-c1de597d70fb.png)

 - OS: Win 10
 - Browser: Google Chrome 86.0.4240.111

**Comment by dcbroad3** [comment]
Thanks for the report! I don't play Krastorio; are there other mining recipes missing? (I think I've specifically wondered about imersite?)

**Comment by LunaticChicken** [comment]
Yeah, as I can see imersite is missing too
