### ISSUE TITLE
Krastorio 2 space science pack has the wrong recipe 

### ISSUE THREAD

**Issue by mchoquette** [factoriolab/factorio-lab#270]
**Reproduce:** "Base: Krastorio 2", select 1 space science pack.

**Current behavior:** 100 rocket parts + 1 satellite = 1000 "space science packs"  (in the rocket silo)

**Expected behavior:**
1. 100 rocket parts + 1 satellite = 1000 space research data   (in the rocket silo)
2. 10 blank tech cards + 5 space research data = 5 "space science packs"   (in a quantum computer)

This breaks planning because both the silo and the quantum computer can have productivity modules, so the rocket part estimate FactorioLab give is too high.

(I put "space science packs" in quotes because in-game they're called optimization tech cards, but the icon FactorioLab is using is right)

**Comment by mchoquette** [comment]
I checked just now, and this is not fully fixed.

Reproduction: same as before ([example link](https://factoriolab.github.io/list#z=eJyFVMuSozAM/Js9QLlqklz2Mh9jbCWosC1Wloea+foVEGZNSGbJgahbyHq0PL7n0Tow2SEkfasxNKdf+X1gm4UY6dw0HVK0ORshE60IcOvIhp05jsCGGI7gGKxA67h4MIT1Vx5ZPs2kNJsrBmErSMmcXhHnV8SlvWqyBlMGnik9YrQsuZ191D4SGIEzitZLk1+Je1JPfFmP2Je2QGthA5sb02QmIm8mlH5Nrw2Ubqa3yYN/cv4ax7jS1WHvqAL3jlfI3PGduXX8CK6JVfDW+wq7hX34h4bUzL38R+jxlIgJWFWxlv8PV78s6Exna5StNjSC2JB36PSCydrJ2sSAjlKNCEA4JKUSTju7hGup8yhsE5ZozpffT9B92Y+VzSNvd2VXs/xTdNBfFTDX9t3lPVyVXDPkBhBzLVrXIiwbIyW0R6L/9Ew3SMb1QVfWQ5tF99i8lP9KP8O1XVUKuaiekPiHSJvHD9SyCv+PsLgd+WpCVWbVhCp0WcJvs2l0Oa3/sHqxeaN6h9gF1EOidb2Obd5dCOCEVZ46x5nyjCGYOFza+lvVTNJbcoe5HiI6u2guyUzpyJNoTo7iWKoJqlipGZl8cYIfqDdY1P8B9N7KI2iozWyWjLPmUYLl2bEDqzJf4a1PeuulPBKLskGa+Tnrr2lOb29/Aa8qMWk=))

Current behavior:
1000 space science packs
  --> 714.286 space research data
    --> 71.4286 rocket parts

Correct behavior:
1000 space science packs
  --> 714.286 space research data
    --> **510.204** rocket parts

**This bug affects vanilla too:**
 - [Example](https://factoriolab.github.io/list#z=eJwrsC0uSExO1S1OzkzNA9JATraWoYGBgVqRbVF+cnZqCVCoqERLq6AoP6U0uSSzLLOkUjcXyM5J1TXWplhUrdhWCxUYAaEWyAkAJGg0mw==).
 - In this example, the silo has 4 prod3 modules in it, but still reports as needing 100 rocket parts to produce 1000 space science.

**Comment by dcbroad3** [comment]
I don't think you're right about this. Productivity in rocket silos gives you extra rocket parts per input, it doesn't give you extra rocket launches per rocket part. When the extra orange bar fills in the rocket silo, you get an extra percent towards your next rocket, not an extra launch. If this wasn't working correctly, you'd need 100 rocket control units, 100 rocket fuel, and 100 lds per 1000 space science, but you can see that they are reduced by productivity. 
If you still think this is a bug though I'm happy to discuss further.

**Comment by mchoquette** [comment]
I double-checked, and you're totally right; thank you!
