### ISSUE TITLE
B+A not working

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factorio-lab#272]
When I select Aluminium Plate and Chrome Plate from Bobs&Angels recipe set, certain things go wrong:
1. Flow doesn't show
2. Arrow in the List at the Aluminium Plate row doesn't show
3. Only Aluminium Plate, Chrome Plate and Molten Chrome rows show - no ingredients, no intermediates, no byproducts
4. Dropdown menu of Molten Chrome doesn't show any recipes

I checked the console - TypeError. It traced to 9830th line of code with the following content:
t[n] = t[n].filter(...);
and it says that t[n] is undefined.

Link:
https://factoriolab.github.io/list#z=eJydXNmWm7oS/Zvz0BzWisHuJA/5GIxlmxtAjoDuOF9/a9A84Nz70k3tXZqnUkny40c338S41I+xW0Xdjds0zMM2vR3+DYj+ruQk3g7/DD+U7H+Ktb5uYgStUXQX1kFh+LUNl/r+vCh5HTephr7u+uEC1K1b6ovYVqEo9n/Uj0HJuZZKvL0tDyEu9SQv2yjqttoV/+3l4yHU/xNQbRdRy2F8EQ5S6F7pxEGWVc7/a350PT46tb69vTVf/ll+nOV5qbne3966y0c39xBC1+p1WO6Y/VqJK7TRfKusBqIPiE8sS4I7baHkGRrkKtQk5rVbBzlX3aDqRUAetDjeOlGflfwMvuvzpjiOFKs/u+WuiZsSYva/62WYHqMAaAABSjpcu36tz+Mm6iv0qPrcLUNfppepG8eY5pjLwT0+G14qrOKdCHyFbAyPTUGpdmLwFbIxKGidcnDLZsM+xTjKz53gvoIfwxlIGH9dxcMc/k+TnAfzf5tgmI8waGGYKNE/+5GafM53HJ4dbFebht/Y4X5zYL8zRorrXeIUQPNH3UNO99U3aAtUzypNUJqe2ZuYhQqztsoJcn2W0zkD1Y0Bz6pbFqgnMa7YnQ8FvKTfOlzOf0Q2opBoSoSNqpdzr8QqjGwnzhe1JkbRr0peRALU2yIuBr2NWILrcIZ59Cw7ZYm76D6eMKAhMciDHL2ofcqfMPZYV1LoXhLmgnGAkrmKCVCrG61EIdzLczeuMYYrQohxEQ85sMmBbQTK8RIiw/zRRWngAhYiuBiGyDzAJD+GGJT4I87vsopYDbpEDKxdWiN/hrl3yLbyQF6e83oXy7AYSknoM7ZSsYdBHlavgUmBq7fEYq2UOLIDChxXQonl6iiykOYOi9VW992yz9RX+J+j87ECUKa4DUo8tkaG41KEEk6Z66bc+I/odCKJiaZEtCXiaIlVdBMP2AyE69dwHdyM8XeTttFKGY5VzDBd38XFzC2uZAW+ecHbcn4OCueBYdSTQdwlSnzQMVKlpB2dCo+FUio+W0ijMJicAg7vYcauVkol1iikZAZYKZqQfxHJToZp2JQS8chCCvlRR7w3HUtUv2/zTxw+h7SrBXzzgm9f8McX/OkF/17g1bbc2WYqlcBplMrgNEqlcBqlcqjnsnbjbj6sRjEfVqOYD6vxOh+lGnUahTp94ExaLoihC6UwdL4IB92iBU7X8z4bTfKa41LlQ1KeclSzk51mNzvNbpJNOcl2J8l2N8l2pwba3ey05ewcd7Jz3M3OcTfJYznJ006Sp90kTzs1cNrNzqmcnfed7LzvZud9Jzvvu9l5L2fn226S33aj/VZftmUtUA/5iQZMjvy+m+b33TS/l9P8nk0Tt1Bk4rpK87aXtAuPvTAM8rpJNgvZFLieaQqimRNi+z2AUS99s/A8SFzqYe3s/W+wnnypCaRVCUGAgk3A7L70X3IpXYeeN3GODYPVn1JeQkuPuO0MO0fv0wRDG+083GBfK8SFtS20rWC5qRAUt9sCRR/Qq+DBP4V4OMUJogITJ4rToHG0Gs/ErJkw8l8buoqyGWSqlA6z5FxJSQ2HOd7VzeSXCZtdeXY+EXJw3SVs6Wv00ghm7d6O9oWEcT/Lql/RzBqHBRsSRLJGXUDn1WWRPZDdwMp6P+f4uOcDxB0ICJZ0l5Fn4Luz3FZtzGOBTVCghxFK3tgPdmFh7IwYorUfrHEXHUT4u7/jKFYR6YK7mI/2IxeBp5dEYZM+2Y9sFG1Ee1FA4uRCegwPqD7ypWIFS4VeNwmzxbPqO3WW2ocJMSp0SRvQ868cMlhTGTNbz2PrNt9gb8faeQbDwFQJ8yV0eJwzIVo1QE1amDeHver6nxjB3D3u671D/o5TI3UfO2EZdIKq6GaxiJTSXSjB9TYjwWlf7VDYgW6jhIjZiUUe5wRV3SfNYEBQNzP77UMMQPGF6nA2pybhs45wDsYGsMUPJYwvkJtIbivtVoli/Cn0PltPwwlCMWlPoPnwSxFDpH4R8wLjcgmd/z7hgXLs5pW20/Xhy5cQaGKgjQHqFBZCDyPU/Li6jmj22udRVO7cxq8Dwngi0YLtlNwWehGn5ZpXracFdTemUYIKCbHhjDtuIkvwYUWOgeU6xhcYhJdsXMxkI2MqF9u4KZWUY3mMw0yLYC4ZQ+ZTMqyfGCevpeGPnTL26MbRlEdqUFqv/JAxtROKd/RLlPSOlheXKVS5CAUNiGODEW5t1eoCk5Ba6wNMlFBBWmoCqQ2kYyCdAukG9YbHLZF8juR+g07+0dGEG+v6nA2HVlSN8zkMaljGvxTwQwFvAlyfh8CicijgJf22ugyAJq7+LAqx8BkDTJ5g2MAcCs1y3dTc9aLM8JC1dKJfAqJw5QTz+jBPkvsp1v47vJRp45Qk3yibAs+L6mDFypLmNBeASsAaOsNEusoaPp8jdlnnuRe/H7CaDR9iqfyjNxgsag6Rq9qGtYJVTwk+zuBTHR5ftV7cIhGXgU2dh+VuiCvgwggj2KJ8aETnzsaYhV7JMtuxz0Q+RHITyS3L2q41wY14CMUmFHXYh2I70wS28iGSm0g24bfxUc8btCJUINTtiO2R9KU8zG3IXKiZlXz1QgoZzag//jVYzpwSXQ9jO5Ry6un8VOHNDbzEURtjkBF9dOx96xNpOrxHA4y4s5j/YLcOAmur9TLweTGFI0sNSeiGPfZqk7Yn154Zk3C447hsYCfHhBtRyLjBaSR5wxLrk+886s+DgQLfctHBJjOeg8JaNCzmPKwcha6FEMSjUYvCKvYIpwZCt+sVbd91kssDxhbrWuMOBbCmu9mztwjbRmjsINUQgtyPdKiOMBpmpGKS1sVxVREzcoxgyJFUk03e4lGVWrvvLn53plrDrIONCx1O4H6AepmxBz3I24Uy2j+7OVIkKFEch9t95asjobpHJIH0PY8wgAYTZWXu8lhNFTqvGNS3N0JNDfrKw3hx3iO2sXnydzuEUG4iuY3kY0XbuMBC53LrO0uHSITEpzONJB9uIjGv1UZiXusYiXmtUyTmtd4jMa/1NRLzWt8iMdL6hH22CI5S9RaPaN2WRaXEGREDeqI13oTE8xADgf6Jadpd2S+TCH1TBB9P2kDaLe9d3jAuawccEqRJkDZBjglysoizIGKkSZA2QY4JYmPGf0GWDdDEQBsDxxiASO36YRcBnChxLqU7InUHrfuszO1GN5QI4a3uT9VdYQ/dbXxYCpP0BcyusSK3WxCIEZqp3Sdk3HPQ0fwUNpbx1/Vi1Tcw3ZJkuF+bkBveECAHJ5WFk9nnYc7CnZrVS28lauI2PsHShNXAvxTK6ylnqUjgrQX6e/FXIV87WHk1ASsMGLYjV0RUWO2uSvFhjXMDK2mwghvY+twjoImB1gJyHLdV6CrylmnNo3vK1p6/zd7nG5//EDex4tTP/kXRzUuZLqRRUtpJCIznnXRgEnEsuYEPodiEoq0xfZpgtdkuiRpolbDOz+byJVuXWc74KA2HOzHoZDI2igxP9oftghEbljDu6593PLRhJy5g692/S1k5N2gwtCcY8VjPF7VNgcDbLr8/j9sZct/NazXJEW0k5+z3bgmVuWaHaw1H81MaJIQL2sc8fDIwX7dK8xrhTQFvC/ixgNt07XWtNOmUaspUW6aOZepUaTd30O7+pKO/eeY1xn+VbA3mrYcJX7EXITiPs9tY2yehhBmwyYFtFZyN+EJgMgR6oRCZIsEphy9EJkh4YFR/wpDRo32HstXxWkWX5oUSF8UOZrrm5DYlj+5BvljYLN+5XmOkSZC2eoBxJ1a6zGRb3GJRB7GE2fp4BPSAUYAubZfNuk5Gmy4ULCzpaPZIfYqRY/g0IsvQZiLDhAc8Dg/Gu4eHZ+UOzxwJOTKsNA9O6s1y4bmQ3hJ7RmqCNCnUptAxhU4JlEbVpFGlSBq3i9rZwDHSJEibIMcEsTGLm1cbKNj48F9QVxZIVdoEOSbIKUaSaJokmgRIoj1Vv7ZOrX/4unaFRgd0gsvWr8PHsD7dDrXI2C1aSaMpMy/DtmXmZdhjmXkZ9lRmXoZ9LzMvw34tMy/DfiszQdjgudQhA5W1mwxU1m4zUFn7mIHK2qcMVNZ+z0Bl7a8ZqKz9LQM5be07Da1b/ULtLOWykl0eAVDNEmb5FVYnXgjM7d88zPd+HRde3i/gJlD4esGGycFeEL0IBvoh5ivrxw+BcoAFysE9c+99RAnxAkeVZZ9PlBAvqFtAA+0E9oKY5xe+foh5ysmt8yzqBYhul2cwX1m/5giUA8xT9u+Tx0CgZp5khLoh6gXgNxq+so+wonmVFFjuulh8jIdPfTSQU2LfzDJ2N98KbRKkTZBjgpwS5D1BvibItwT5niCXYYHq38jejTnfXVDm0hLRW9hKe29wK0PPuXBT7e1b9IMY3fbsMvMFXb/kCHID3HmhXHWzinnASNY7mdP0qirUIv+Id/LHqDnusPt1DetbQLnk9KxQzI6575Pnfgqz1zGImpNc6ft5f4TRojPeVM0dOhufbcpol1lCWM9hwgT7j4DFP1EI5xH1QD4MCiDjkPEgd6LFIB12GIFmyWIde+7QlLmmzYwH2vpz2kA0PleG7HyIB5PPMY6Sd+Tk0RxMPaITLEkFfV8JyHdw9TffhNQuTnzL6D71cPxw6RLK73i70dUwwd5WVaM885ghFxWBB2Qg6JFVVNbVgbx+SDo+XVtpHV7injDZpi2ROJfzcN7hG+k+tI84Zkxxw8kliS5TXa4b4ydUBkxpeLD5YVPwRyk0KfUC7WPUKN2QxgsFINO7pdpcNYqBJgbaGDjGwMkCy2c3Pbw4WW4iuY3kYyS7+FYxPQRV2yGDNRmszWDHDAZpPOR8E5ldO18XjG6SwlaVpokQNZNHiLrJJ8T53Fuf/kfclI/K867GlJ2mQpgtY5cIzhbxjY48vHsJZC8Ic6FmVsrd5Mgo7OY6oxldOflrcOcuS1k9Vzzyd+lPtqfQtsiVIAebeJGLNPXDkcD8yehlIiqkndFMSv6XYDbb7LhszEdbRS7R4KgEaZ4w+N6ini18ofWFoy+cfMFedQzEcyiGFx2LlAmVXHPMwoc83Piwf8cxCxe028qb/7i43uQXA20MHGPgFAO22hLonEJh9e3SfuikGovUoUw1MeVXaZHaCQVVexdqgvHBFxv8jQJu34KtEgI8rtfgKRRfZrELSBgmKXZS2KSIIdBWaUmT8iWlMi56NIlwwMUABDI/VeJZIh/Sbk46FsKrbxojw2bWkv2xDxat9R5IbrcSwuYqAqH2QIkk+ftpv0P7niBenfkznFvwB354G8ptSte47sMVjZwYaTSi11fYv1yqzBUXfY2YbVpf8M205AZy5vKxhuw2guyxpfvkbasvNYHUkoQDkm7K+kJNhzrVq1s65DPwu+bbG750mvho7aJgb0HPjM4QbHr8Bx1bR79yoDrxx5eQtIQWuIngO3ODOlor8OnKDBrX7YY22tjhD9vgX/rFH/piZ5/x3cEmQVbdsojpTAfOE51coetRm/iwE1os2lZUQm3lXWFxGdFfe6zcA3Olla6j7MwFZfyBCEbtydiD3ogwSA5GPtSgx9f0hgG3usDrXOCR+sxXPjkyM62I36vSd1ndU5MNerp7OEC7ZhO380uYMh3NsRvdC0aR31DgLxjR4yy8yGEr2P5iRmJdHKthJhc2XsC2mPEiudQWyOXsXHkeQW8XyLb8gM535AtFtqb6saMf4YANCA4NLimTsK7BHneUkruMHaGGldfrcud37cDelNwgA66Lhb8ORI9Y9dGu+WGNVX7qh4FgIq3Qlfkwye0Cuf/60WjU1hd2bn2XXN/3wLJgDZmK5NymFWxx894xYhp30RWzxQ8ljyEIFhBPE9KcRFvq6Fv2fo6vUOGCfdDVRwd7afNzFFgVnVKCqoYrkH7i7NopXE7wIaxbK/ytVciYTVyI2v0iwv46Rs8y7dNNb8nFZLVhQ586BobRve/GSC+nB/nq+XEwDwZpJHwZY3wVXiB+/wszCv3iCz4QQMScKZJw7zzB6vKZXYjRY9YQ4it19n3k2/5BUXhi8QazLEwpMBLatze0jCY2QroZtp1QCWeYi/8LqPiE7Q==

**Comment by dcbroad3** [comment]
Thank you for the report!
It looks like this is due to the calculator having two copies of the aluminum plate, one with id "angels-plate-aluminium", and one with id "aluminium-plate". The one you picked is "angels-plate-aluminium," which doesn't actually have any recipe associated with it. It looks like it gets its id changed to "aluminium-plate" during startup. The real "aluminium-plate" item can be found in the Other (question mark) tab. 

I'm going to address this by removing fake items like this that have no recipe from the data. Have started work on that already but also found issues with the Bob's and Angel's icon sprite sheet, so will take time to fix those also.

**Comment by dcbroad3** [comment]
test
