### ISSUE TITLE
Handle different numbers of beacons

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#292]
Need a way to handle factory configurations where some factories have a different number of beacons than other factories. For example in many smelter setups most furnaces have 8 beacons while the ones at the ends may have less.
It is currently possible to enter decimal numbers in the beacons input as an average but this must be calculated by hand.
One option would be to add a dialog that can help in calculating the average. Another option would be some way to have multiple rows in the steps that could have different configurations.

**Comment by SteveS8** [comment]
The latter would be the most intuitive I think. Fractions are inconvenient. And you can already select the same recipe multiple times. It just gets added together below

**Comment by dcbroad3** [comment]
I'm trying to figure out how this would work, though. I'm imagining there's a plus button next to each row that lets you split a step. Then you can specify different settings for each row. This will require a lot of work behind the scenes as it's not designed to have multiple but oh well. 
The big problem is how to divide the items between the two configurations. Presumably you want to define a number of factories for each row, but what happens when the numbers you put in don't match up with the items required? Maybe it only allows entering a number of factories on the "added" steps, but even then it will be common to end up with surplus.

**Comment by dcbroad3** [comment]
Generally, I've seen a few requests like this where users want to enter a number of factories with specific configurations, *instead of* a specific number of output products. Then you get the inputs and outputs for that number of factories. That might end up being a totally different page.

**Comment by dcbroad3** [comment]
Another option: You can already specify the same item with a number of factories in the list. What if, when you specify a number of factories, you have the option to override the settings for that recipe? So you could specify 8 iron plate factories with 8 beacons and 2 iron plate factories with 6 beacons, for example. The list of steps would still give you one row using a single set of settings, but you'd know it was equal to the factories you want to use and you'd still see the total item output of your factories.
This is my new favorite idea as it's powerful without over-complicating the steps list.

**Comment by SteveS8** [comment]
I don't think it's necessary to add functionality to split each tab. This could be restricted to the input rows at the top. So instead of selecting iron plates once you can do it twice. 

And you can already export existing rows to new tabs. So you could do that and then you split the product into two inputs manually. Like clicking Plus, manually subtracting some factories for one row and then adding them to the other so that the total is the same as what you started with. That way it also works with belt numbers or items per time.

Personally it would be perfectly fine if it worked with one product on its own like that. Instead of being part of a whole production chain.

**Comment by dcbroad3** [comment]
I'm not sure I'm following you now. Does it make sense to you to be able to just provide specific settings at the top when you pick the products and number of factories?

**Comment by SteveS8** [comment]
I meant something like this. There would still need to be a line that adds up the totals of course
![FactorioLab](https://user-images.githubusercontent.com/48756893/100553342-dd545080-328d-11eb-89c8-48b95c5009e0.jpg)

Makes perfect sense to me

**Comment by dcbroad3** [comment]
Okay, that makes sense. My suggestion is just to add the factory/beacon settings inline in the top two rows where you define the number of factories to use. Then in the bottom the resulting steps would be the same as they are today (combined), but would add up the items using different factory settings.
