### ISSUE TITLE
Calculated Sankey node width

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#293]
Currently, Sankey node width is hard coded. Since some configurations have a small number of sets, the hard coded value can look excessively small sometimes. The width of the Sankey nodes should be calculated from the number of columns in the Sankey diagram.

**Comment by IgNaCy07** [comment]
And when diagram gets a LOT bigger, it's often hard to see what's going on. I don't think it should always fit in one screen width - when the calculeted width gets to some minimum value, the diagram shoul just get wider, not denser, so it's still readable
