### ISSUE TITLE
Negative values when heavy prodmoded

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factorio-lab#294]
When using machines with lots of high-tier modded productivity modules, the negative speed effects stack and result in negative speed.
Factorio Wiki says that moduled machine's speed cannot be 20% lower than not moduled one's.
Here's the link (note the negative power usage):
https://factoriolab.github.io/list#z=eJyNWNuW2ygQ/Js82OGcjCfZc/YhH4MQkshw0XLxRPv1W1wkCwl7k4ckVEFDN91Fy/NPGrxR1AujiWOCa8bJTNnH5e2L+CnFP0H0ZFp6awYZjBWMUCb6y9vXkTrS8+C5FUFhPEu6cEsGSxXHkPZ3ClM9ma1h3DmhRxK08KDwt9BGEiqlWTDuLHVuNzL6X/4YUoc9mbAsCE86Q23cnJl5xmY+6NF5rrfZG4DT+HgMJ6Rg8Ax7WtHztLSj0hPM4tsRvrifDj5zwn/P0tgUjMulbJJMXbnkzONou8M4bzS/CoBljg5McooYBJi2/OH51Qi5D8TE6X25OnipvUDsEURYs5yqBFpm3Dxxy8lgZE9oC+xaIGuBfQvkLXBogWMLnFqg0C3UBH+ELWU+2NMRCoxLySsQEaO4TzmnqVyccEQF6YWb411QSd7+cN7tD+e9b/O0UZgmtBPj5Hf71PjtCf7MzvcDvq+30yY1SbQhHbeLlCi3OLMThsCbiWpOvCHMhp4T5NnKORn6kT/Fe46y8FQJnbL9wA6IFBmEm1r4XWAdl1SPvEV/GtMXXJpRMMS1imMDvz3B35/gKY4Qig9Uek89RawsnedYaSAYtaMhs+lbMIrwg6N2cePF7RZeh7o5I+h4MYk2OXtHxbXHiMoWmrTE5Kw/cPsrqqkkLs1FRmlxRmNY1pO310XALtAx3yYnI9WrxQIy+oo/JMeZD5LRJ7snPT3BwWL+bsdyeiJDh1KGglYoSuGTRj0VLE3vBczadGO9FfeEZS1HiXUIetRjPAZUkbdv316xf/14wf54uRZsm74bkWqFq9kv+9cgxghr7YPsqLXHZ+VIVvmeGSkG7sI8Iwa1Uc3tuNSVecBuDey9gaVqHIyNR49OvR3Gt8P4/TBO60cZm4AqO/BKIikmwWVfXKqRNRev57Rseb1VZpNcxa5JxgdCIBnTBPMJ8YTrCC7EOuQ3q9ILRUfNfewUdgFXMSvFUQxP6K2JvjfR7wVN5w/upFs1lSWoge/koGZ6Yf1yhotEnIndfRyJLLU1utV7DZd6PxNVcijer/pb/hubMIeoZ0im1KqkQFM0s8iRUkDGNsG1/VgJD5TG1qQJbrMD6jqq1cjlcbw+0xE3neP2nrvt1CqTDlr58YKqrzT6qOgjM1OR74hHF3nou/e3Ngd5RyY5dOeO6iRAlvaCppDlRpgZg809GRDSV7yOZSxfzXAomMTn5zP1xrlPoLko16xM4tXqSzJhOVuYLELgBBq3HCp6HHcnQB2RE+BOwMmKO5txR+S46LTkOD7ue9r2vGvZNMeYzi5IXut+Ff4TgH9l30YrJTjQTxloJbdxwBtWd2TDBPKl+BR7uGf4WmGZy1801fQNqmcK/at0avX0Gq/XKGFtloX9OM7hVtP92T+pnQ+GN6i2mdL8MGxmeeoU1vYlI9BHEpucj1r7Slh1j8cHLQ3SoJOJ8PiQUqZfNCwztz14IVZ6+0nE96ouefP/s7IL130Xty/ry2VtkYU019jiwA8KPXr0PXA42kEnJuXVDIObYqs3BzVf41+/oqIL+AUZiw/dEBB2tgv7wUFJu/i1buxSyVqK3qYX0DCGbivLZLlXziDI6ZNiZwINCFddWqIomwSC//5Yc2Z39qgO2CVZiZ/6lg/gMWATV2mbORVjEr/q+dnH+3xOfPpsFmpfS6XUadSwMPLUiRxDVUhrPv1UrSo/XazHxwtmxRDGna9F57Fby2T5mWTtgNr74qlCVrWYrcUZaGru/b4aZ4o+HrlIKGPYxz5hIWVS9PuaK29jjMVh0bSsAmWPHqLub/vb3348eBZLehftCZr/Du4xs1SvmuNvZ7mHK8kNpxzeQ96AyEiVQsextDgkCG6S3psLozemRfwu1ko379F2OSV87irSv09Y1I7qnrJZXxFkWV7i7HT5MQPgBQWQlSu20Kjm+IL9fUWPDf1Zh5f4x8UM5/N68rhJKpQO3R0Czrn+D3ni1kc=

**Comment by dcbroad3** [comment]
Thanks for the report. Energy usage is being properly capped (I believe) so this is hopefully just a matter of implementing the same cap on speed.
