### ISSUE TITLE
SE data from space probes

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factorio-lab#296]
Add recipes for data from space probes from SE.

**Comment by dcbroad3** [comment]
Do you think you could be more specific? I haven't played SE and if the recipe isn't already included then it likely isn't treated as an actual recipe in-game (like the rocket launch recipe). Is this a single recipe or multiple?

**Comment by IgNaCy07** [comment]
There are (I believe) three recipes: Asteroid belt probe -> Asteroid belt probe data, Star probe -> Star probe data, Interstellar void probe -> Interstellar void probe data. They're all rocket launching recipes, and I've got an idea. The 'rocket-launch-product' property of an item prototype describes what is made when that item is launched in a rocket. You can just make recipes like that: item + 100x Rocket Part -> item.rocket-launch-product[2]x item.rocket-launch-product[1]

**Comment by dcbroad3** [comment]
I'll likely investigate this in tandem with the "burnt-result" property you brought up in order to add the nuclear reactor recipe cycle recipe. It makes sense to use both of these in place of hard-coded recipes.
