### ISSUE TITLE
Add a wagon picker

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factorio-lab#303]
Currently there is no way to change a cargo wagon used (or I missed it). Since there are mods that add new cargo wagons, it would make sens to add a picker just like it's done with beacons.

**Comment by dcbroad3** [comment]
I'll be honest, this has crossed my mind and I hoped no one would ever ask for it.

**Comment by dcbroad3** [comment]
Is there a good mod you know of to test this with?

**Comment by IgNaCy07** [comment]
Bob's Logistics add tier 2 and tier 3 cargo and fluid wagons - with 50% and 100% more than the base one, respectively. Prototype properties to obtain are inventory_size for cargo and capacity for fluid wagons. Hope I helped!
