### ISSUE TITLE
Industrial Revolution 2

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factorio-lab#305]
**What mod are you requesting?**
Industrial Revolution

**Is this mod set compatible with the latest version of Factorio?"**
Well, it's complicated. The latest compatible version was 0.17, but because of license violations the mod is now deprecated and author is working on Industrial Revolution 2, which will release (I believe) as soon as 1.1 gets stable, so I'm not requesting it for now, but for the time of release of IR2.

Looking forward to it!

**Comment by dcbroad3** [comment]
Didn't know there was an IR2 planned! If possible, add a comment when it's actually released.

**Comment by dcbroad3** [comment]
To keep the backlog manageable, I'm going to close this issue since Industrial Revolution 2 is not yet released. When it is released, feel free to reopen this issue or create a new one.
