### ISSUE TITLE
Wrong Recipe [Pyanodons]

### ISSUE THREAD

**Issue by LonnonjamesD** [factoriolab/factorio-lab#313]
**Describe the bug**

**To Reproduce**
1. Go to settings
2. Click on base, and click on Pyanodons
3. Enable the Automation Science Pack Recipe
4. Use it as the recipe you want to calculate
5. Recipe is wrong for current version

**Expected behavior**
The recipe should include a petri dish instead of a mushroom

**Screenshots**
![image](https://user-images.githubusercontent.com/55360995/102908727-d9a78a00-4445-11eb-843b-2c172d7000f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by dcbroad3** [comment]
@LonnonjamesD The current data set for Pyanodons does not include the alien life mod. My current plan is to address this by adding Pyanodons + AL as a separate option in the dropdown list. Would this be good enough? I would imagine there are players who prefer to play without alien life.
