### ISSUE TITLE
A way to see total number of factories like power/pollution

### ISSUE THREAD

**Issue by ghost** [factoriolab/factorio-lab#330]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dcbroad3** [comment]
Do you envision this being broken down by factory type, or just a simple number added up? I would imagine the former could take up too much space, and the latter wouldn't be very useful.

**Comment by ParsleY123** [comment]
I am not sure. My goal was to see how many factories I going to save by using 12 beaconed setup instead of 8.

**Comment by dcbroad3** [comment]
Maybe I can do this as a simple number in the totals row, with a button that opens a dialog with the number of each different factory type.

**Comment by kekal** [comment]
I would like to add that we need to sum up the quantities of factories rounded up. Otherwise, it doesn't make sense.

**Comment by Karmacopper** [comment]
To throw my 2 cents in on this:

I was discussing it briefly with ilbJanissary on discord (#dyson-sphere)

I would suggest this be an "open in new tab" feature or alternatively incorporated into the flow page.
All factory/belt totals rounded up. 
Columns:
Factory type | Total | Product | Factory # | Output Total | Belt requirement | Power requirement 

Rinse and repeat for each product from the same factory type along the row.

The Last row is a summary of factory type, belt, and power totals.
