### ISSUE TITLE
Unable to add any recipe

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [factoriolab/factorio-lab#331]
pressing the "+" icon has no effect
This happens on the default microsoft edge browser with no extensions, as well as the browser I actually use
![Screenshot 2021-01-14 224605](https://user-images.githubusercontent.com/68972888/104691007-51ba4600-56ba-11eb-8e54-0042cc381f3e.jpg)

**Comment by AmericanPatriot6f0** [comment]
I seem to have lost the add label functionality somewhere, but this is a bug.

**Comment by dcbroad3** [comment]
Thank you for reporting this. I was worried something like this might happen, but I haven't been able to reproduce it. If I'm not mistaken, you should be able to open an incognito window in any of these browsers and use the site without problems. If I'm wrong about that, then there is a bigger problem here but I can say that the website is definitely working for me. 

Could you possibly send the value of the "state" key in the browser's local storage? In Chrome, the steps are:

1. Right click anywhere in the page and select "Inspect"
2. Go to the "Application" tab of the developer tools
3. In the left navigation menu, expand "Local Storage" and select "https://factoriolab.github.io"
4. There should be a few keys, or at least one. The one I'm interested in is the key "state".
5. Double click in the value column and you should be able to edit/copy the value out.

If you can copy it and send it I should be able to reproduce your problem and determine a fix. 
Feel free to message me on discord via @ilbJanissary as I want to get this resolved ASAP; I doubt you are the only one with this issue.

**Comment by AmericanPatriot6f0** [comment]
It magically fixed itself, but not on edge.
The key on edge is:
{"productsState":{"ids":["0"],"index":1,"entities":{"0":{"id":"0","itemId":"follower-robot-count","rate":17,"rateType":0}}},"itemsState":{"iron-ore":{"ignore":true},"copper-ore":{"ignore":true},"crude-oil":{"ignore":true},"steel-plate":{"ignore":true}},"recipesState":{"iron-ore":{"factoryModules":["module","module","module"]},"copper-ore":{"factoryModules":["module","module","module"]},"speed-module-3":{"factoryModules":["speed-module-3","speed-module-3","speed-module-3","speed-module-3"]},"productivity-module-3":{"factoryModules":["speed-module-3","speed-module-3","speed-module-3","speed-module-3"]},"speed-module-2":{"factoryModules":["speed-module-3","speed-module-3","speed-module-3","speed-module-3"]},"productivity-module-2":{"factoryModules":["speed-module-3","speed-module-3","speed-module-3","speed-module-3"]}},"factoriesState":{"ids":null,"entities":{}},"settingsState":{"preset":3,"baseId":"1.1","disabledRecipes":null,"expensive":false,"belt":null,"fuel":"electric-furnace+electric-mining-drill+assembling-machine-3+oil-refinery+chemical-plant+rocket-silo+offshore-pump","flowRate":1500,"displayRate":1,"miningBonus":12,"researchSpeed":250,"inserterTarget":1,"inserterCapacity":null},"preferencesState":{"states":{},"columns":{"Items":{"show":true,"precision":1},"Belts":{"show":true,"precision":1},"Wagons":{"show":true,"precision":1},"Factories":{"show":true,"precision":1},"Beacons":{"show":true,"precision":1},"Power":{"show":true,"precision":1},"Pollution":{"show":true,"precision":1},"Link":{"show":true,"precision":1}},"linkValue":2}}

Looking at it, it seems like the bookmark I had (I bookmarked a specific factory) is no longer compatible or something.
