### ISSUE TITLE
"Flow" section font size/scaling decreases when resizing view or switching sections.

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [factoriolab/factorio-lab#332]
The flow section font can become extremely small and impossible to read after performing certain actions. Fixed by reloading page.

**To Reproduce**
create a factory
go to the flow tab
resize the window using the drag-able dongle

or

create a factory
switch between flow and list tabs

**Expected behavior**
font size should not be affected by former actions or reloading

Normal (you may also note that text can be difficult to read due to overlap)
![normal](https://user-images.githubusercontent.com/68972888/104771448-2883cf00-5727-11eb-9cf7-b625b34f4f01.jpg)

Switching between list and flow
![switch from flow to list tab and back](https://user-images.githubusercontent.com/68972888/104771451-2a4d9280-5727-11eb-8573-56f20903617d.jpg)

resizing with window resizer
![window resized](https://user-images.githubusercontent.com/68972888/104771459-2b7ebf80-5727-11eb-9e31-1944dc497b09.jpg)

Windows 10 chromium browser

**Comment by dcbroad3** [comment]
Fair enough, this is kind of a known behavior I hadn't considered a true bug but it's annoying enough that I'll see what can be done about it.
