### ISSUE TITLE
DSP Research Speed Bonus

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#352]
Add handling for Dyson Sphere Program's research speed bonus effect.

**Comment by glcoder** [comment]
Mining productivity should work just fine already (but this setting is missing with DSP mod selected for some reason).

The research on the other hand is need to be supported.

**Comment by dcbroad3** [comment]
Should address this later when actual research recipes are added to the DSP data set (or when requested), currently this doesn't appear that it would do anything regardless.
