### ISSUE TITLE
DSP power calculation is not correct

### ISSUE THREAD

**Issue by ShadowTheAge** [factoriolab/factorio-lab#358]
https://factoriolab.github.io/list#p=titanium-plate*1&s=dsp******1

It looks like only "drain" power get calculated

![image](https://user-images.githubusercontent.com/7020122/106601982-65e0bd00-656d-11eb-9981-f532bcc0b7e9.png)

Also vein mining should not calculate power because people can cover the same amount of veins using different amount of miners (and definitely more than one miner per vein). Better to calculate nothing at all (data.json fix)

**Comment by ShadowTheAge** [comment]
Just noticed that something is wrong with vein amount calculations also. It should be 2 seconds to mine 1 titanium vein baseline
Every vein (except oil) is 0.5/s

(I have +40% mining speed and placed a miner to touch one vein)
![image](https://user-images.githubusercontent.com/7020122/106641548-62166000-6598-11eb-9aea-9564833d309c.png)

**Comment by hhrhhr** [comment]
> There is a mining speed parameter for every vein but it is not used.
It is used for manual mining. (`int VeinProto.MiningTime`)

Some numbers (from assembly):
```
// water-pump
int MinerDesc.minerType = 1 // EMinerType.Water
float MinerDesc.periodf = 1.2f
SInt64 workEnergyPerTick = 5000
SInt64 idleEnergyPerTick = 200

// minig-drill
int MinerDesc.minerType = 2 // EMinerType.Vein
float MinerDesc.periodf = 2.0f
SInt64 workEnergyPerTick = 7000
SInt64 idleEnergyPerTick = 400

// oil-extractor
int MinerDesc.minerType = 3 // EMinerType.Oil
float MinerDesc.periodf = 1.0f
SInt64 workEnergyPerTick = 14000
SInt64 idleEnergyPerTick = 400
```

Also game have a variables `GameHistoryData.miningCostRate` ("Ore consumption/Miner product", reduces the cost of ore during mining) and `GameHistoryData.miningSpeedScale` ("Mining Speed", normal mining speed multiplier). So mining speed from 1 vein is `(60.0 / periodf) * miningSpeedScale`.

Water is extracted at a rate 75/min * _miningSpeedScale_
Ores —  30/min * _number_of_veins_ * _miningSpeedScale_
Oil — _number_of_veins_ * _oilSpeedMultiplier_ * _miningSpeedScale_ (_oilSpeedMultiplier_ = 0.00004, _number_of_veins_ — hidden value).

**Comment by ShadowTheAge** [comment]
> Water is extracted at a rate 75/min * miningSpeedScale
that is not correct. Period = 1.2 means 50 periods per min = 50/min.

**Comment by hhrhhr** [comment]
Yes, 60/1.2=50 ;)
