### ISSUE TITLE
DSP - Hydrogen and Deuterium from Gas Giants

### ISSUE THREAD

**Issue by oggi42** [factoriolab/factorio-lab#360]
First of all: I love the DSP calculator, thanks a lot for supporting it here!

Would you please add a recipe to obtain Hydrogen and Deuterium from Gas Giants?
Seems like the calculator does not know Hydrogen and Deuterium can be mined as "basic resources" like ores and sulfuric acid but from gas giants.
If I remember correctly there are also Gas Giants for Fire Ice and Deuterium maybe add them as a recipe too.

I tried to calculate how to produce 60 Rockets per minute and disabled a lot of recipes. I tried to find the least complex solution by using all the "advanced resources" like fire ice and crystaline silicone for example. The calculator did it's best and made me produce 5000 excess Graphene as it was the only way to get enough hydrogen.

**Comment by ShadowTheAge** [comment]
Unfortunately H and D mining from giants is random and the formula is not simple because miners also uses some of it to power itself

So the recipe should be added to satisfy the solver but it should be just "nothing to hydrogen" type of recipe

Also the relative ratio of mining giants is about 0.04 D to 0.96 H but it is slightly random on every gas giant (+- 10%)
The actual numbers may be higher or lower together (so 0.03 to 0.7 is possible for example). That may be taken into account I think

I suggest adding fake recipe: nothing -> 1 D + 24 H

**Comment by dcbroad3** [comment]
Thanks for the info @ShadowTheAge. @oggi42, do you agree with this approach?

**Comment by sergiizaskaleta** [comment]
based on my observations there is not "use some of it to power itself" part - all resources as listed on the tooltip are produced, albeit at 10x speed compared to what is listed. i.e. Gas giant with `1.22/s Hydrogen` and `0.06/s Deuterium` produced 1340 Hydrogen and 56 Deuterium in 120s of operation. -- could be a bug, or `speed: 10` is in order for orbital collector.
Regarding approach to take - i've used fake recipes without "mixed outputs" and pure production of D, H and fireice from gas giants in my fork.
If there is any randomness,

**Comment by ShadowTheAge** [comment]
No, I have read decompiled code just today. There is a part that it is uses some resources and there is also mining speed part. I have the exact formula.

The important part is the ratio and it is about 24:1.

**Comment by ShadowTheAge** [comment]
Here is the formula, you can try to use it on your gas giant:

`M * (8*miningSpeed - 30 / ((D+H)*8))`

M is either H or D whatever you are calculating
miningSpeed is 1.4 if you have +40%

**Comment by oggi42** [comment]
Wow! So many answers in such a short time. Thanks everyone :)

@dcbroad3 I definitely agree with the aproach. A fake recipe for H and D from nothing would solve my problem.

@ShadowTheAge I found one of those Ice giants on my journey to a neutron star. Wanted to find out if you can mine strange matter directly from them. Turns out you can not :( They are just stars...

Did anyone test if the Gas Giant Miners stop producing Deuterium if the Hydrogen Stockpile is full?

**Comment by ShadowTheAge** [comment]
I think they don't. But that will just be shown as an overproduction that you can ignore.

**Comment by ShadowTheAge** [comment]
Actually there is an automation way to generate fake recipes. The file is called ThemeProtoSet fields GasItems / GasSpeeds. There you can get ratios, they are then multiplied by random number between 0.9 and 1.1 (independently) (I think that randomness can be ignored) and by star richness (together)

There are also several types of planets with the same settings, should merge those

@glcoder if you would like to

**Comment by glcoder** [comment]
Sure. According to data (as @ShadowTheAge stated above) there are two options of gas collection for Gas Giants:

- Hydrogen 0.96 + Deuterium 0.04
- Hydrogen 0.3 + Fire Ice 0.7

In fact the underlying calculus of final mining amount of gas is depends on many things:

- Original gas collection speed.
- The distance to the planet's star from the home star.
- Some random coefficient (from 0.9 to 1.1).
- Orbital collector energy usage.
- Gas energy value.
- Mining speed bonus.

We don't have tools to implemet such calculations, so let's just fake it. The base rates with all assumpattions and without mining bonus will be about:

- Hydrogen 4.08/s + Deuterium 0.17/s
- Hydrogen 0.84/s + Fire Ice 1.95/s

Mining bouns isn't just simple multiplication, in fact 50% mining bonus will give about x2 mining rate. Let's just ignore this for now.

PS. @ShadowTheAge fun fact, I've got this ice giant next to my starting planet :)
![image](https://user-images.githubusercontent.com/1660779/106773444-1aeca580-6652-11eb-8a73-2195816b89bf.png)

**Comment by ShadowTheAge** [comment]
Also please fix the export script so it states 0.5/s mining for each mining recipe except oil ignoring vein mining time

**Comment by glcoder** [comment]
> Good. Also update the export script so it states 0.5/s mining for each mining recipe except oil ignoring vein mining time if it is not done already

Yeah, already read about this in other issue, will do!

**Comment by ShadowTheAge** [comment]
I think that giant mining  also shouldn't show energy used :)
https://factoriolab.github.io/list#p=quantum-processor*1&s=dsp******1
2/3 of the energy while you don't see it at all

**Comment by glcoder** [comment]
> I think that giant mining also shouldn't show energy used :)
> https://factoriolab.github.io/list#p=quantum-processor*1&s=dsp******1
> 2/3 of the energy while you don't see it at all

Yes, you are right, I think we should disable energy consumption for Orbital collector, I'll fix that.

**Comment by ShadowTheAge** [comment]
Also gas mining shows that it takes 8 seconds to mine 4 hydrogen. While "8" in the orbital collector is mining _speed_, not the mining _time_ (so, the opposite)
Should be 1 second.
