### ISSUE TITLE
DSP vein mining speed is incorrect

### ISSUE THREAD

**Issue by ShadowTheAge** [factoriolab/factorio-lab#361]
https://factoriolab.github.io/list#p=titanium-ore*2&s=dsp******1

Just noticed that something is wrong with vein mining data also. It should be 2 seconds to mine 1 titanium vein baseline
Every vein (except oil) is 0.5/s
It is correct for iron for example

There is a mining speed parameter for every vein but it is not used.

(I have +40% mining speed and placed a miner to touch one vein)
![image](https://user-images.githubusercontent.com/7020122/106641548-62166000-6598-11eb-9aea-9564833d309c.png)

_Originally posted by @ShadowTheAge in https://github.com/factoriolab/factorio-lab/issues/358#issuecomment-771838832_

**Comment by dcbroad3** [comment]
To confirm, the current data set also has stone as 1 per 1.5 seconds, which also seems incorrect, although I can't seem to find any data on stone vein collection rates. 
I'll update to: 
iron-ore: 1 per 2sec
copper-ore: 1 per 2sec
silicium-ore: 1 per 2sec
titanium-ore: 1 per 2sec
stone-ore: 1 per 2sec
coal-ore: 1 per 2sec

gas-hydrate: 1 per 4sec
diamond-ore: 1 per 4sec
crystal-rubber: 1 per 4sec
grating-ore: 1 per 4sec
bamboo-crystal: 1 per 4sec
mono-mag-ore: 1 per 4sec

oil: 1 per 1sec
water: 1 per 1.2 sec
sulphuric-acid: 1 per 1.2sec

**Comment by ShadowTheAge** [comment]
No, all the rare resources are also have the same mining speed (one per 2 sec). Just confirmed that with crystal-rubber.

Water is correct. Sulfuric acid I have not encountered yet but that is pump mining speed so should be the same.

Oil depends on a node, like in Factorio. There are nodes from 1/s to 5/s and probably more. (Probably should not display power for oil for the same reason as for veins.)

**Comment by glcoder** [comment]
Just checked that, the MiningTime in a prototype file is a speed of manual mining, not applicable to Mining machine. I'll remove usgae of that parameter from export script.
