### ISSUE TITLE
TypeError: Cannot read property 'toString' of null when clicking on Plastic bar

### ISSUE THREAD

**Issue by RadoslavK** [factoriolab/factorio-lab#364]
When I click on the plastic bar under items in the list, it shows a TypeError.

**Additional context**
It seems to happen only with a [link](https://factoriolab.github.io/list#z=eJylUkFywyAM/I0P1HTiZnr0Y2QhJ5piYISctr+vkjqdaU1O5QKjXRZplzLCqnkB5Zx8RaaE5Avgmzs8v/Yxn7gq4x5ZOLKCfO4RPNPCCHGPFMlhxfZLq14FG3LVTrQrdzxSJFTJybpDFlxZnaOPIlSrV4FUSxb1E0Xt2Wi+RFByboaqf3HMpZDcGQ9EqhLFjTP0tt+MmUCamp2MkvGN1GNO1mb0a7IOoVZapsjp5BfAMyfyLzYiUfCLmROpzdikCogNebfxcvXr+5Y/Pv27amG/+0Cp3mJQMcIqD/qBcAGLI/w432Q1EmryNvsRpgfzd/M4bGqmtXC6okE4RkfzTL8ncce+oTFs+c2rJPtQXR2drZojB6tRdG5ww+HwBaT4IBo=) I saved for 30 SPM base. And it also happens when I do the same with Light oil.

**Comment by dcbroad3** [comment]
Let me know if you still see any issues with this, it should be fixed now.
