### ISSUE TITLE
[DSP] Item/s Option.

### ISSUE THREAD

**Issue by norsehealer** [factoriolab/factorio-lab#366]
> **Is your feature request related to a problem? Please describe.**

Most of the game has a default of items per second, there are a few items listed as item per minute.  The math can get fuzzy having to switch between I/M and I/S.

> **Describe the solution you'd like**

Add a dropdown item selection for Items/s

**Comment by dcbroad3** [comment]
So you can already switch to display rates per second in the settings, are you basically wanting to override the settings based on picking either items/s or items/m in the drop-down?

**Comment by dcbroad3** [comment]
@norsehealer please let me know if this is still necessary considering you can choose display rate in settings (per second, per minute, or per hour). Otherwise I will close this issue.

**Comment by norsehealer** [comment]
> So you can already switch to display rates per second in the settings, are you basically wanting to override the settings based on picking either items/s or items/m in the drop-down?

sorry, i'm use to forums that give a notification and easy access to get to the thread (still working on learning github despite being here a while).

i didnt know there was a settings, and i see now there's a rate per second.  i just figured it was at the top where the item/m was. 

i apologize about this.

**Comment by dcbroad3** [comment]
@norsehealer that's ok! I'll consider maybe putting that drop-down in a more obvious place, maybe next to products, just to make it easier to find.

**Comment by norsehealer** [comment]
> @norsehealer that's ok! I'll consider maybe putting that drop-down in a more obvious place, maybe next to products, just to make it easier to find.

i dont think it would hurt if it could be an option under or above the Item/m you have on the main page. but i'm sure a great design decision will be made.

**Comment by dcbroad3** [comment]
Reopening this since I am addressing it in a PR, even if it is addressed in a different way than requested.
