### ISSUE TITLE
Add support for input items (or "items produced elsewhere")

### ISSUE THREAD

**Issue by joequincy** [factoriolab/factorio-lab#368]
**Is your feature request related to a problem? Please describe.**
Often when building large factories, I break things down into sub-factories responsible for certain components. For a simple example, when planning out a new production line for e.g. Chemical Science Packs, I'll just draw off my existing Green Circuit lines rather than setting up extra Green Circuit capacity in the new line. I can still use the calculator for this, but for perfect ratios I need to adjust the new copper and iron capacity down to ignore the portion that's allocated to Green Circuits. It would be nice to have a way to set up items as inputs to the calculator so that they don't need to be constructed within the plan.

**Describe the solution you'd like**
I suggest adding a section to specify inputs (or "items produced elsewhere") into the calculator. These could use the same sort of UI as the "products" section, where you select zero or more items, and the amount per unit of time available to your new factory. During calculation, these would be treated as raw materials available for use in the workflow.

For example, if a user indicates they have 300 Green Circuits/min produced elsewhere:  
- If they want to produce 100 Chemical Science Packs/min, they wouldn't need to produce any more Green Circuits. The workflow would just feed the input into the Red Circuit production.
- If they wanted to create 150 Chemical Science Packs/min, then the workflow would add the additional 150 Green Circuit/min production capacity to support that.
- If they only wanted to create 50 Chemical Science Packs/min, then the workflow would just have excess Green Circuits available.

Here's a rough mockup of how this might look on the Flow screen:
![image](https://user-images.githubusercontent.com/3322920/106835316-6011d700-6654-11eb-91e0-c527d3b41856.png)

On the List screen, these inputs could be omitted from the list entirely, as they're indicated in the box where the user entered them... or they could be added to the bottom of the list with the "factories" column indicating that they're produced offsite.

The section to designate inputs could be hidden by default and only exposed when an option is enabled in the Settings, something like
![image](https://user-images.githubusercontent.com/3322920/106836592-b2ec8e00-6656-11eb-91bd-877d4d536548.png)

**Describe alternatives you've considered**
I don't have any alternative suggestions - this would be a purely additive feature, so the alternative would be to simply not implement it. 😄

**Additional context**
This could also be an alternate approach for users to solve the DSP problem described in #360, where it's a common pattern to vacuum up gasses off-site and use logistics to transport them to the factory. Users would be able to indicate that e.g. they're producing plenty of Deuterium elsewhere, and they just want to utilize that supply without needing to account for it inside workflow produced by the calculator.

As an extension to this idea, instead of selecting a fixed rate for inputs (e.g. 300/min), the user might be able to instead select "as much as necessary". This would then calculate how many of the given input item are needed in order for the calculated workflow to work, much like mined raw materials. If this option is added, it would make sense for the List view to indicate those materials with the required rate (and again, an indicator in the "factories" column that they're intended to be produced offsite).

**Comment by dcbroad3** [comment]
Thanks for the detailed writeup! It's somewhat different from what you've asked, but have you tried clicking on an item in the list?
![image](https://user-images.githubusercontent.com/8430702/106898186-de589280-66c1-11eb-860e-ad8f9de4e574.png)
The item icon grays out, and the calculator assumes you are importing that item from elsewhere and doesn't try to calculate any inputs for it. (Note: This functionality was copied from the [Kirk McDonald Factorio Calculator](https://kirkmcdonald.github.io/calc.html#data=1-1-19&items=advanced-circuit:f:1))

The main difference I see is that this doesn't account for a factory that needs e.g. 400 electronic circuits but only imports 200.

**Comment by glcoder** [comment]
On the other hand It will be interesting to make and save custom recipes, just specify inputs and outputs click save and from now on calculator will use this recipe to produce items. )

**Comment by dcbroad3** [comment]
@glcoder now that's a completely separate request, it seems to me.

**Comment by glcoder** [comment]
> @glcoder now that's a completely separate request, it seems to me.

For sure!

**Comment by joequincy** [comment]
@dcbroad3 I had tried that in the context of the DSP gasses, and didn't achieve the desired effect. I didn't think to try it again with the Factorio calculator. I see that it does cover the specific scenario I described above, so oops there I guess! I might have uncovered a bug on the DSP side of things?

Over there, as part of a larger factory, I'm using Fire Ice to produce Graphene, and importing Hydrogen from off-site (I have the X-Ray Cracking recipe disabled). When I click the Hydrogen icon to disable it in the list, there's no change. The calculator still lists enough Chemical Plants to produce all the Hydrogen I need on-site, which then has me producing around 8.75x the amount of Graphene I need.

Taking a closer look, maybe this is related to the fact that DSP has multi-product recipes? When I click on the Hydrogen in the Flow view, the bottom panel doesn't have either the "Inputs" or "Factory" tabs (the Graphene does). And while the Hydrogen lane is visually connected to the Graphene recipe, that recipe doesn't indicate Hydrogen in its outputs.

<details> <summary>Graphene has "Inputs" and "Factory" tabs:</summary>

![image](https://user-images.githubusercontent.com/3322920/106935678-e839c000-66d8-11eb-9bce-dc88915f105d.png)

</details>

<details> <summary>Hydrogen does not:</summary>

![image](https://user-images.githubusercontent.com/3322920/106935738-fbe52680-66d8-11eb-89f1-e463dfaad7cf.png)

</details>

<details> <summary>Recipe only shows Graphene outputs:</summary>

![image](https://user-images.githubusercontent.com/3322920/106935846-1919f500-66d9-11eb-93d9-594ca24abc9f.png)

</details>

So maybe because the factory _must_ produce Hydrogen as part of the Graphene recipe, the calculator can't fully ignore it?

**Comment by dcbroad3** [comment]
I think you have the right idea here. It's not possible to completely ignore the hydrogen. If you can share a link, I might be able to troubleshoot further to make sure it's not broken in some way, as it can be very tricky to ignore items that are part of other processes.

**Comment by joequincy** [comment]
For sure. [Here is the setup I had in the above screenshots](https://factoriolab.github.io/flow#p=rocket*15,space-warper*5&i=oil*1,diamond-ore*1,photon-capacitor-full*1,hydrogen*1&f=1*belt-1,assembler-2,interstellar-logistic-station&s=dsp*deuterium+deuterium-formula+gas-giant+ice-giant+x-ray**belt-3****50). Now that #367 is in, I did have to exclude the new Gas Giant recipes to replicate the scenario with it producing excess Graphene. But even with the Gas Giant recipes enabled, (what appears to be) the same issue presents itself, now producing excess Hydrogen so that the Deuterium production can keep up.

**Comment by dcbroad3** [comment]
It feels like there is a bug in the logic, I think even though the ignored item's inputs are being excluded from the calculations, the simplex solver is still trying to make sure enough of the item is produced. I'm going to mark this as a bug and investigate further.
