### ISSUE TITLE
DSP missing recipe for full accumulator

### ISSUE THREAD

**Issue by Black-Noise** [factoriolab/factorio-lab#380]
Parser seems to be missing proper handling for the accumulator charge/discharge recipes using the energy exchanger, this is somewhat relevant because gas miners need full accumulators to build.

**Comment by dcbroad3** [comment]
@Black-Noise could you elaborate on what the missing recipes look like?
@shadowtheage & @glcoder, do you recognize what might be missing here? 
From what I can gather (as someone who has not played DSP), this looks like the equivalent of a Factorio accumulator, and since this calculator is not intended to account for energy production (only giving amount of power required by factories), this is outside of the scope of what would normally be included in the calculator.

**Comment by Black-Noise** [comment]
> @Black-Noise could you elaborate on what the missing recipes look like?
> @ShadowTheAge & @glcoder, do you recognize what might be missing here?
> From what I can gather (as someone who has not played DSP), this looks like the equivalent of a Factorio accumulator, and since this calculator is not intended to account for energy production (only giving amount of power required by factories), this is outside of the scope of what would normally be included in the calculator.

In dsp there are 2 items, "accumulator" and "accumulator (full)", you get the second by either manually placing one on the floor and letting it charge (very slowly because 600kW for 90MJ), or you feed it with a belt into an energy exchanger (iirc that's the name), which is a building with currently manually set "charge" and "discharge" modes.

In short, the missing recipes are:
1) 1 accumulator > 2s in energy exchanger (45MW cost) > 1 full accumulator
2) 1 full accumulator > 2s in energy exchanger (45MW output) > 1 accumulator


They're more like very expensive barrels for energy in DSP. The first recipe is also the only way to automate production for a gas giant miner (orbital collector?). And for completeness sake:
- charging is capped at 45MW but will only go up to the grid's output if unavailable, consuming only excess output. 
- discharge is only as fast as the grid load, though it's prioritized over at least wind and thermal power generation. 
- the energy exchanger itself has a 90MJ energy store, however it seems to only interact with the grid and not for charging or discharging accumulators. 
- full accumulators can also be used in the mecha as fuel rods, though this destroys them instead of turning them into empty accumulators.

**Comment by dcbroad3** [comment]
OK, thanks for the detailed writeup! I think that gives me enough to go off of, I'll take a stab at adding those recipes later.

**Comment by glcoder** [comment]
Ah yes, completely forgot about this one, it was in the first version but was lost in the process, I'll add it to export.

PS. Meanwhile I'm working on preparing standalone toolchain for easy data exporting, hope it'll be complete till weeks end..

**Comment by dcbroad3** [comment]
Since this is more a matter of missing data than an actual bug, going to mark this as an enhancement instead.
