### ISSUE TITLE
Critical photon recipe time incorrect

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#387]
![image](https://user-images.githubusercontent.com/8430702/107639795-5fbea080-6c3f-11eb-8d9b-96f710ee3d6c.png)

The recipe is listed as 1 second, thus 1 factory produces 60 per minute. This appears to be incorrect.

**Comment by dcbroad3** [comment]
@shadowtheage @glcoder Can either of you verify this?
Basically, it looks like the recipe 'photon-capacitor-full' should have "time" changed from 1 to 6, does this look right?

**Comment by dcbroad3** [comment]
https://dsp-wiki.com/Critical_Photon
> A Ray Receiver in Photon mode produces 5 Critical Photons per minute, while consuming 62.5 MW. When a Graviton Lens is inserted, the Ray Receiver consumes 125 MW and produces 10 Critical Photons per minute. 

It looks like this needs to be treated as two separate producers/factories. "Ray Receiver" and "Ray Receiver (Graviton Lens)", where the latter has "speed": 2 and higher energy consumption.

**Comment by ShadowTheAge** [comment]
Yes, it is 5/minute. I don't know if someone uses graviton lenses for the speed boost, they are expensive and you can just build more :)

**Comment by ShadowTheAge** [comment]
I think you can add 2 recipes. The first is 12 sec and produces one photon for free, the second is 6 seconds but consumes 1/40 of a graviton lens.

I don't know about power consumprion. It does not consume power from the grid, it instead consumes power from the dyson sphere. Not very useful to add those.

**Comment by glcoder** [comment]
Noted, I'll add this recipes to automated export.

Don't know about power tho. I think it's too hard right now to calculate correct power generation and consumption without some additional code for DSP part of Factorio Lab.Need to think aout this.

**Comment by dcbroad3** [comment]
If it's not power on the grid, probably fine to just leave it out. https://calc.dsp-wiki.com seems to treat it as the same kind of power as other buildings, but sounds like that's not really the right behavior, I'd rather be consistent.
