### ISSUE TITLE
DSP: make Hydrogen loop implicitly part of Fractionator recipe

### ISSUE THREAD

**Issue by SimonSapin** [factoriolab/factorio-lab#390]
**Is your feature request related to a problem? Please describe.**

Any Dyson Sphere Program production that involves the "fractionator" building produces technically correct but very unhelpful Flow graphs like this:

https://factoriolab.github.io/flow#p=strange-matter-generator*1&s=dsp******1

![image](https://user-images.githubusercontent.com/291359/107868837-e8c81880-6e87-11eb-8e83-876aa1a2c1d5.png)

The fractionator consumes hydrogen as fast as the input conveyor belt can provide it, turns 1% of it into deuterium in one output belt, and returns the remaining 99% unchanged on another output belt. The only reasonable way to use it is to loop that remain back in, and indeed this is what happens in the graph. But the throughput of that return loop is ~100× the numbers we care about, so showing it proportionally-sized in the graph makes everything else unnecessarily small.

**Describe the solution you'd like**
Consider changing the fractionator formula/recipe so that the loop is an implicit part of it. Instead of `100 hydrogen → 1 deuterium + 99 hydrogen` make it `1 hydrogen → 1 deuterium` (at a rate of 1% the belt speed). That way, big numbers not relevant to "how much stuff do I need" are hidden.

If this change is made, it may be useful to also include a couple sentences in the recipe details that show up on hover, to explain what’s going on.

**Describe alternatives you've considered**
Instead of changing the recipe, I suppose the flow graph could have UI to hide individual edges? Though that seems more work to implement and harder to make it good UI/UX.

**Additional context**
Although having each fractionator building in its own hydrogen loop is optimal in terms of production rate per fractionator, it takes a lot of belts so in practice players are likely to make loops with several fractionators daisy-chained. Assuming conveyor belt Mk III, the first fractionator gets 30 hydrogen per second input but the second one "only" 30 × 0.99, the third 30 × 0.99 × 0.99, etc. The efficiency loss is small but it would be great if factoriolab can compute it accurately. (The hydrogen to deuterium conversion ratio is still 1 to 1.) The overall conversion rate over time for a chain is `sum(conveyor_belt_speed * 0.01 * 0.99**i for i in range(fractionator_count))` (assuming Python syntax).

As a further refinement to the above change, the formula could be for a loop and chain of a *configurable* number of fractionators. This is pretty much another feature request so it might be better in a separate issue, but it’s very related to the above so let’s have it here for now.

**Comment by dcbroad3** [comment]
I've been thinking about doing this for a while and have had a couple other users bring it up. I think you're right that visualizing the loop is not helpful in this case.
