### ISSUE TITLE
Flow graph overlaps sections

### ISSUE THREAD

**Issue by Randelung** [factoriolab/factorio-lab#391]
The graph overlaps intermediate results, completely hiding some.

I believe this link will get you to my current setup: https://factoriolab.github.io/flow#z=eJxdjksOgzAMRG/DwmAJqLrkME5IwVJ+chIEt28KrYTqld94bE+cbFg4ZdaYMmUOHgaAf62jlIxT1ggOMHSMjrLwDk94dMsd9A2a1wTK2Ixjk6Y5RdCU2LGglqPetWi3sf30UhRuhn37G1RB1Vd269uZyQU/n95FKK7GmxM8+ZCLuiCS1LR1U1MkzTnIKSe2rLk4XHlZMRbhfFyDYuNaUWN1z9fzHYUO+CaGWmP/BpB/ZRA=
If not:
![image](https://user-images.githubusercontent.com/3729270/107875035-dcf74900-6ebd-11eb-9487-0352949ac8f9.png)

I would expect the different sections to appear in full and not overlap.

![image](https://user-images.githubusercontent.com/3729270/107875060-0adc8d80-6ebe-11eb-805e-2444a541268c.png)

There's a diamond under those coils...

 - OS: Win 10
 - Chrome 88

**Comment by dcbroad3** [comment]
I've seen multiple complaints about this. I'll look into it a bit but as far as I know this is actually a bug in an external dependency, either d3-sankey or d3-sankey-circular.

**Comment by kekal** [comment]
> I've seen multiple complaints about this. I'll look into it a bit but as far as I know this is actually a bug in an external dependency, either d3-sankey or d3-sankey-circular.

I am not familiar with the project and d3 flexibility. Still, as a user, I really miss a certain display mode, when I could see the "waves" of production without considering quantities, ratios and other same stuff.
Probably, if you build such a view from _**equal**_ rectangles, the cause of this bug will disappear.

The closest mode is the diagram with Link value "None", but even it makes the bricks depend on the number emanating/incoming lines. 
Just N factories with X recipe, which accepts M belts. Without graphics that make complex diagrams difficult to read, like this:

![image](https://user-images.githubusercontent.com/13663141/108126990-3d031080-70b3-11eb-915c-eabf2b9187e7.png)
