### ISSUE TITLE
Incorrect DSP recipes

### ISSUE THREAD

**Issue by JiangengDong** [factoriolab/factorio-lab#426]
The following recipes in DSP are incorrect. 

1. In version 0.6.16, we cannot produce critical photon with gravity lens any more. 
2. The two products of orbital collector should be separated to two different recipes, since they do not affect each other. 
    For example, when we are collecting on the ice giant, even if the collector is filled with fire ice, it can still collect hydrogen. 

I am trying to modify the `data.json` and will try to start a pull request later, but I am not quite familiar with them. So I think it is better to report it here in advance.

**Comment by dcbroad3** [comment]
Thanks for the report!
Is any action really required for your item 2? As you noted in your PR, separating those into two separate recipes results in likely bad behavior, it looks like you need double the collectors. With them combined into a single recipe, it's still possible to produce 'surplus' of one item or another, which is basically the same as the collector producing one while it's full of the other. Do you have a suggestion of how it could be handled better?

**Comment by JiangengDong** [comment]
I think the benefit of splitting the recipe into 2 is that the solver will use collectors for most of the hydrogen production. For now, the solver tends to use a small number of orbital collectors but a large number of fire ice to produce hydrogen, which aims to avoid 'surplus' production, even though this 'surplus' is acceptable.

However, I don't know a perfect solution for this problem yet. It seems difficult to be expressed in a linear programming problem, and I also don't know how to display the result in the 'List'. So if you think item 2 is not a very significant problem, please feel free to close this thread. I will reply on this thread if I have a solution later.

**Comment by dcbroad3** [comment]
Thanks @JiangengDong ! Per this and the discussion in the PR I will close this issue, unless you can think of a specific way to better handle the collector recipes.
