### ISSUE TITLE
Unclear and conflicting display of rocket silos needed for space science.

### ISSUE THREAD

**Issue by jimbolla** [factoriolab/factorio-lab#433]
**Describe the bug**

The UI is confusing when indicating how many silos are needed for a given amount of space science. Given [10000 SPM](https://factoriolab.github.io/list?z=eJwrcC7VMjQAArVM53Qtw3jnHCDhVA5iZWgZqhU5F2hpaYXGOwPJwPgMLS3nOiDUcowv1NLyrPMEMpz9gFLe8c5FQMpRrVjLWK3MCADgSxbi), do I need 8.24, 11.53, or 8.24+11.53=19.77 silos?

Also, this number conflicts with [kirkmacdonald's calculator](https://kirkmcdonald.github.io/calc.html#zip=RYzBCsMwDEP/JqcG2q2XpfhjssQboY5TYoexv58HK7OMhA56OWqExZturhaGq8sVDvM7yNcTXFZXFKuAHDGhl1SQLa3soYdltnPlya0j9JZ2VJ8aa2/kBxedJCoSGWGi9vIZWYq+vWgfSUfH6bd5DCRXWx6EcnKO2DVscg3r/McE6+dvPIjC/AE=) which shows 10.4. I'm not sure which numbers to use.

**To Reproduce**
Go to the link provided above and view the rocket silo count.

**Expected behavior**
UI would make it obvious how many silos are needed.

**Desktop (please complete the following information):**
Windows, Chrome, latest

**Comment by dcbroad3** [comment]
Well that is bizarre. Last I tested those numbers were always identical. I'm not sure what would have broken it so I'll look into it.
Kirk's numbers are very slightly off because that calculator uses an approximation for the rocket launch time. But I'm not sure what the problem is in factoriolab at the moment.

**Comment by jimbolla** [comment]
Wow great response time. Kudos :D

**Comment by dcbroad3** [comment]
Thanks! By the way I double checked and kirk actually doesn't use an approximation, it's just a wrong value. It has the rocket launch time as 2475 ticks when the actual amount is 2420. It should look pretty dang close though either way.
