### ISSUE TITLE
Satisfactory [Experimental] Request

### ISSUE THREAD

**Issue by Carroty06** [factoriolab/factorio-lab#438]
**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factorio-lab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.

Yes.

**What mod set are you requesting?**
E.G. "Bobs and Angels", "Pyanodons", "Seablock", etc.

It is not a mod, It is a completely different game. Since a completely different game like Dyson Sphere program was added to factoriolab. I would like to request if you could add Satisfactory [Latest Experimental update] to Factoriolab. I'm aware that there are other tools for Satisfactory that help calculate production values but they don't seem to operate or provide the same kind of easy to access information as Factoriolab. If there is a website/tool that is similar to factoriolab please let me know. I have not found one so far.

EDIT: Since Update 4 is now out on Early Access. I would like to request that the latest early access update be added to Factoriolab instead.

**Comment by happymy** [comment]
This calculator is very suitable for planning and calculating factory output. I recommended to wait until the EA version is released.
Because the official may adjust the balance again.

**Comment by happymy** [comment]
Updata 4 has been released！！！
PLSPLS PLS Let calculator support it.
@dcbroad3

**Comment by Kazmodah** [comment]
There are already a calculator for Satisfactory but is VERY messy. Especially with endgame recipes that makes the thing take some minutes to calculate anything https://satisfactory-calculator.com/en/production-planner

**Comment by happymy** [comment]
> There are already a calculator for Satisfactory but is VERY messy. Especially with endgame recipes that makes the thing take some minutes to calculate anything https://satisfactory-calculator.com/en/production-planner

https://svaini.github.io/satisfactory-calculator/calc.html

this is better :)
