### ISSUE TITLE
Bug: Productivity Module Speed Bonus

### ISSUE THREAD

**Issue by Schnobs** [factoriolab/factorio-lab#441]
**Describe the bug**
The calculator assumes a -15% speed effect for all productivity modules.

In my vanilla game, the slowdown is only -5% for Productivity Module 1 and -10% for Productivity Module 2.

Stats for consumption, pollution and productivity seem to be fine, it's only the speed modifier that's off. Could you please have a look?

**Comment by dcbroad3** [comment]
Could you send a screenshot or a link that demonstrates the issue? As far as I can tell, the numbers are all correct, it shows -5% for level 1 and -10% for level 2.

**Comment by Schnobs** [comment]
Just mouse over the module in the list: http://factorio.schnobs.de/prodmod.jpg -- this shows -15% for lvl-2.

Without modules, the assemblers in the screenshot would consume 900 iron and produce 450 cogs / minute. 

With the modules as shown, (2x prod-2 & 1x speed-1) it should be 900 in, 504 out. As you can see, I'm getting 810/453.6, which is exactly 10% short; consistent with the calculator assuming a slowdown of 15% for each of the prod-2 modules rather than 10%.

**Comment by dcbroad3** [comment]
Are you using the "Base set" 1.0.0? In that set, the speed effect was the same for all three levels. In 1.1, it was updated to be different for each level. I can confirm that I see the behavior in your screenshot when I select "1.0.0", and I see the current vanilla behavior when I select "1.1.25".

![image](https://user-images.githubusercontent.com/8430702/113046628-47163580-916e-11eb-8e25-1bad78e3bda3.png)

**Comment by Schnobs** [comment]
Now that you mention it... as a matter of fact, I do. Set a long time ago, and never looked at again.
*feels embarrassed*
