### ISSUE TITLE
Mining recipes

### ISSUE THREAD

**Issue by ickputzdirwech** [factoriolab/factorio-lab#445]
It would be nice if we could not only see how much ore is needed but also how many resource entities. Right now you have to calculate this manually with mining productivity and productivity modules in the miners.

This would for example help calculating how long a resource patch would last.

**Comment by dcbroad3** [comment]
Could you give an example of the kind of result you're looking for?

**Comment by ickputzdirwech** [comment]
Sorry if I wasn't clear. I realise this request is a bit weird. Resource entities is maybe not the right term. What I am looking for is the needed richness. Here is an example:

Let's say we want to produce 100 iron plates per minute. We use productivity module 3s and have a mining productivity bonus of 110%.
[Factoriolab](https://factoriolab.github.io/list?z=eJwr0DKMd0rVMjQwUCtyytXScqtzi3fKAdN1bmrFWmDgVKpWZgQA-U0Lew__) tells us we need about 83.334 iron ore per minute. To get the number I want I have to divide by 2.4 (1 plus 1.1 from mining productivity plus 0.3 from 3 productivity module 3s). This gives us about 34.7 which is the richness a single resource entity loses per minute to supply 100 iron plates per minute.

**Comment by dcbroad3** [comment]
OK, got it, so in addition to the amount of iron ore consumed you want to see the amount of iron ore being drained from the actual patches on the ground. It seems like a reasonable request, I'll have to think about the best way to go about this.

**Comment by lilred** [comment]
You can look at Factory Planner for inspiration, it already supports this.
