### ISSUE TITLE
fractions showing up as integers

### ISSUE THREAD

**Issue by branor04** [factoriolab/factorio-lab#446]
**Describe the bug**
values in flow view are rounded up integers after enabling fractions. 

**To Reproduce**
1. select copper cable in the production tab
2. click on flow
3. click on the cog
4. enable fractions for items
5. click confirm

**Expected behavior**
in the case of the copper cables, it should show 1/2 on both copper- plate and ore production

**Comment by dcbroad3** [comment]
Thanks for the report, I can repro and I'm looking into it.
