### ISSUE TITLE
Decimal beacon counts are rounded up but only if fractional part is at least 0.5

### ISSUE THREAD

**Issue by ajmurphy520** [factoriolab/factorio-lab#451]
**Describe the bug**
Entering decimal beacon counts where the fractional part is less than 0.5 works correctly (eg 3.1, 3.2, 3.49). Any count with a fractional part of 0.5 or greater is rounded up (eg 3.5 - 3.99 rounds up to 4)

**To Reproduce**
1. Add recipe with factory that allows modules
2. Set beacon count to any value with a fractional part of 0.5 or greater
3. Beacon count immediately rounds up

**Expected behavior**
Count should stay exactly as entered

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Firefox
 - Version 87

**Additional context**
Setting the beacon count using preferred settings doesn't round up.

**Comment by dcbroad3** [comment]
I think what you're seeing when you use beacon count less than 0.5 is that it is rounding down to 0 and then not emitting that change. From what I can tell, using 0.4 beacons has the exact same result as using 0 beacons. That input is *currently* only designed to handle whole number inputs.

There is an older issue in the backlog to handle different numbers of beacons, https://github.com/factoriolab/factorio-lab/issues/292. One suggestion is to allow decimals/fractions in the input, another is to handle it more elegantly and allow specifying, say, 5 factories with 8 beacons and 2 factories with 4 beacons. That way you don't have to calculate the fractions yourself.

**Comment by ajmurphy520** [comment]
It does calculate the correct number of assemblers if you set the decimal beacon count using the preset settings. I can see uses for both solutions. Allowing a decimal average is useful if you have a tileable design with at least 2 machines for a recipe but with different beacon counts. If you wanted to know how many of those tiles you needed or how many inputs the tile needed as a whole, a decimal/fractional beacon count is more useful. If instead you have a design where the beacon count is the same except for the last machine then the other solution is more useful.
