### ISSUE TITLE
Update Bob's Mods to include all available modules

### ISSUE THREAD

**Issue by DaleStan** [factoriolab/factorio-lab#462]
**What mod set are you requesting?**
Bob's Mods also includes pure speed modules, green modules, pure productivity modules. and god modules. These modules are not available to either produce or use in the Bob's and AngelBob presets.
I haven't played enough AngelBob to know if Bob's modules work properly in AngelBob, though.

**Is this mod set compatible with the latest version of Factorio?**
Yes

**What mods are included in this mod set?**
This is the same as the existing "Bob's Mods" and (if applicable) "Bob's & Angel's" presets, but with the startup settings for Bob's Modules changed to include god, green, pure productivity, and pure speed modules.

**Comment by dcbroad3** [comment]
Ahh OK, so it's something in the settings. Sure, I can adjust my settings and re-run to build new data sets.
