### ISSUE TITLE
Fractional math off when combining items

### ISSUE THREAD

**Issue by werelord** [factoriolab/factorio-lab#463]
Fractions appear to be off when combining products of the same item.. 

Example, in the DSP version of the app: 

![image](https://user-images.githubusercontent.com/1413880/115734003-ffd72b00-a34e-11eb-8f15-3b110da53ffe.png)

Actual math should be:  0.25 + 0.3 = 0.55

Display shows as: 0.56

**Comment by dcbroad3** [comment]
If you switch to display actual fractions it is correct, but it is mistakenly rounding 0.550 up to 0.56.

**Comment by dcbroad3** [comment]
Looks like the internal function rounds 0.55 using (Math.ceil(5 * 100)) / 100, and JavaScript had a floating point error where 55 * 100 = 55.00000000000001, so this reduced to 56 / 100 and then 0.56. 
I can fix this by doing the math using the internal Rational library instead, which has better precision than JavaScript floating point numbers.
