### ISSUE TITLE
Suboptimal recipe for fish

### ISSUE THREAD

**Issue by jDomantas** [factoriolab/factorio-lab#468]
Recipe used for fish is 100 rocket parts + 1 space science pack. The actual optimal way to produce fish is 100 rocket parts + 100 space science packs, which effectively reduces rocket part cost and required silo count almost a 100 times.

![image](https://user-images.githubusercontent.com/8329015/115965242-e7266b00-a530-11eb-97d3-7a4cc46e09c9.png)

**Comment by dcbroad3** [comment]
Can you really do that? Where does the 100 number come from? If the silo is set to launch automatically, would it wait for a full 100 space science packs?

**Comment by jDomantas** [comment]
100 is the stack size of fish. If you put more than 100 space science packs into the silo then the amount of fish you get is capped to 100 to avoid going over the stack size, but putting in less than 100 is basically a missed opportunity.

Good point about automating this. I tested it out and you can get 12 per launch by having a stack inserter put in 12 science packs in 1 swing. The rocket starts launching immediately though - even if you have more stack inserters to put in science packs in the exact same tick only one will succeed. So 12 fish/launch recipe is viable to do automatically, and getting more seems to require manual work.

**Comment by dcbroad3** [comment]
Given that this recipe is an obscure use case in the first place, if the devs don't even see the need to address filling to 100 before the auto launch, I will leave this as-is in FactorioLab as well. Changing to 12 per launch would likely just be confusing. Even changing to 100 per launch would likely be confusing to the average user. 
If you feel strongly that there is a right way to address this then feel free to comment further but for now I will close this issue.
