### ISSUE TITLE
Allow selection of the default beacon in the Settings pane

### ISSUE THREAD

**Issue by DaleStan** [factoriolab/factorio-lab#470]
**Is your feature request related to a problem? Please describe.**
I'm at the point in my Space Exploration run where I'd like to select the Wide area beacon as my default beacon in the Settings pane.

**Describe the solution you'd like**
I think the best solution is to make the non-clickable beacon image on the Settings pane into a clickable button, like the factory-selection and module-selection buttons.

**Describe alternatives you've considered**
The workaround is for me to simply select the Wide area beacon for every recipe after setting up my desired products.

**Comment by dcbroad3** [comment]
This sounds more like a bug because as far as I know it should be configurable in settings like it is in the products list.
