### ISSUE TITLE
Add small Up and Down (▲ ▼) arrow buttons to increase/decrease numbers input by click

### ISSUE THREAD

**Issue by 93Magick93** [factoriolab/factorio-lab#485]
Tiny arrow buttons Up/Down (▲ ▼)  to increase or decrease number input by 1 per click. Specially useful when calculating by number of factories.

**Comment by dcbroad3** [comment]
The fields used to have these when the inputs were marked for numbers only. Now that they also support fractions the inputs accept any string and the up/down arrows were lost with that change. 

I'll have to look into whether it's possible to add the arrows back manually.
