### ISSUE TITLE
Calculator thinks I am going to mine the crude oil and not pump  it?

### ISSUE THREAD

**Issue by DRY411S** [factoriolab/factorio-lab#497]
**Describe the bug**
See the final line of output at https://factoriolab.github.io/list?z=eJwtxc1qwlAUhdG3yeCAJSo-gCe5-95GTbT-RJ0ELFZ0IILooIPv2QvaNVm3k.U.BqPu-C40.-.f915lh0n20-.G3a2rsntu5gVe4gGPeI0v8A3e4luKAaUIPUJFqAkN4YIKVKKAhCJK6BNVaIJmqEYNmqMF-kJLtEJrtEEt2qId-kZnInFKXBNbUk6qSVfSnfTLw6wws7HlNsyewz.bqUVD

Calculator thinks I need a LOT of mining drills to pump the oil.

**To Reproduce**
Use that link above

**Expected behavior**
Should be pumpjacks

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser Chrome
 - Version Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by dcbroad3** [comment]
Thanks for the report. Looking at the generated data file, the lua generator thinks crude oil is produced by mining drills in Krastorio 2, I'll have to look into why. 

```json
    {
      "id": "crude-oil",
      "mining": true,
      "producers": [
        "burner-mining-drill",
        "electric-mining-drill",
        "kr-electric-mining-drill-mk2",
        "kr-electric-mining-drill-mk3"
      ],
      "time": 1
    },
```
