### ISSUE TITLE
After the updated version of the Dyson Ball Project, the antimatter fuel rod formula has been changed and a new furnace has been added.

### ISSUE THREAD

**Issue by myshowtogo** [factoriolab/factorio-lab#498]
**Is your feature request related to a problem? Please describe.**
After the updated version of the Dyson Ball Project, the antimatter fuel rod formula has been changed and a new furnace has been added.

**Describe the solution you'd like**
According to the 5.28 update version, the official has made the following changes:
Modify antimatter fuel rod energy 7.5GJ -> 7.2GJ, consume antimatter quantity 10 -> 6
Added more advanced furnaces, related technologies, and synthesis formulas

**Describe alternatives you've considered**
nothing

**Additional context**
https://store.steampowered.com/news/app/1366540/view/3044975900132654798

**Comment by dcbroad3** [comment]
I appreciate the additional information, but I think this is covered by #493.

**Comment by myshowtogo** [comment]
> I appreciate the additional information, but I think this is covered by #493.

I saw it, thank you, then I close this issuses
