### ISSUE TITLE
[DSP] Wrong number of mining machines

### ISSUE THREAD

**Issue by wzurborg** [factoriolab/factorio-lab#511]
I guess this is a known problem, and it is specific to DSP. The number of mining machines required depends on the number of ore veins that each machine covers, and thus it cannot be precisely calculated.

![grafik](https://user-images.githubusercontent.com/1320950/121183403-526b9880-c864-11eb-934c-a5070291aff7.png)

IMHO it would be better to calculate with an average of 6 veins per machine and divide the number of veins by 6 (rounded up) to get to the number of mining machines required (in this case it would be 9).

Perhaps a tooltip or another form of warning on the mining machines could also be added as a user warning that the number is only an approximate value.

(As a side remark, I can live with the word "Factories" for veins in the top row, but perhaps some improvement is possible there as well)

**Comment by dcbroad3** [comment]
I may instead make this add up the different veins, instead of creating an approximate number of mining machines. In other words this should just show 50 veins instead of 50 machines.

I'm open to suggestions on the column header, but I haven't thought of a better word than "Factories" to describe the intent there.

**Comment by wzurborg** [comment]
That is a good solution.

As for the "Factories" I did not mean so much the column header but the drop-down selection in the user input section. I could try to come up with an improvement to select veins in addition to items, belts, and factories.

**Comment by wzurborg** [comment]
Fantastic!
