### ISSUE TITLE
Specify inputs additionally to products

### ISSUE THREAD

**Issue by kaesaecracker** [factoriolab/factorio-lab#518]
**Is your feature request related to a problem? Please describe.**
It is frustrating to have many recipes in the tables you do not really care about. For example, when I am planning a production station (city block? unit?), I decide which items I want to produce locally and which to bring in by trains. Many times the flow tab and item list is cluttered with stuff that will not get produced locally anyways.

**Describe the solution you'd like**
I would like to have a list of "free" items in the factory settings, or an input section below the products section.

**Describe alternatives you've considered**
- a "hide recipe" button in the list of steps. The hidden steps would be moved to the bottom of the list, and would not show in the flow tab.
- Another alternative (which is not really sufficient for my use-case) would be a checkbox to ignore raw iron, copper, oil and so on

**Additional context**
For example I want all the recipes which are striked through to be hidden, because I do not want to produce them locally.
![image](https://user-images.githubusercontent.com/7461823/121773122-11cc9180-cb7a-11eb-90b1-9478c250314a.png)

**Comment by dcbroad3** [comment]
Have you tried clicking the item icon, from the items row in the list, to ignore it? That treats the item as an unlimited free input. If that doesn't do what you want, could you clarify what you want to work differently?

**Comment by kaesaecracker** [comment]
This is exactly what I wanted, sorry ':)

**Comment by dcbroad3** [comment]
Awesome! Do you have any ideas to make that easier to find, by the way? Honestly you are not the first person to even open and close this same type of issue - I can only imagine how many people don't know about that trick.

**Comment by kaesaecracker** [comment]
Thought about it
- a link in the options screen that shows a tutorial popup (simple change)
- a button next to the current button (hide is a dedicated button)
- a "hide" column you can add, which shows a checkbox (hide is a dedicated column).

I like the third idea the most. I found the column chooser really early
