### ISSUE TITLE
FYI only: AVG Internet Security reports phishing - false alarm I assume

### ISSUE THREAD

**Issue by B3lt3r** [factoriolab/factorio-lab#520]
**Describe the bug**
AVG Internet Security reports phishing

**To Reproduce**
1. Make sure AVG is on
2. Goto the site e.g.: 
--  https://factoriolab.github.io/list?z=eJwrcDLQMjMxMNDScjJQKyrQ0tIyi8.X0vKqA0IwFe-UCxZ0ygFSQHUgIX8tLc86zzq3Ord4l0CwrDGYzIOozAZTLq5QY-IzoAy1NA-QhCfQHLViLaAWJ6BC53S1MmMAZ6gjhQ__ 
3. See error from AVG popping up

**Expected behavior**
I'm sure this is an AVG false alarm. Or hope. I cannot get more information out of AVG beyond the screenshots, sorry.

**Screenshots**
![image](https://user-images.githubusercontent.com/86040558/122341728-18755300-cf44-11eb-966b-1f52975f5478.png)

**Desktop (please complete the following information):**
 - OS: Win10 latest patch level (Home, 20H2)
 - Browser: Chrome latest (Version 91.0.4472.106 (Official Build) (64-bit))

**Additional context**
Using AVG for a long also used Factoriolab recently for many weeks. 
I don't say AVG is the best, but today was the first time I see this so I've added an exception as shown on the screenshot. 
After checking the history I've found the same alert some days ago, but nothing before:
![image](https://user-images.githubusercontent.com/86040558/122342471-f8925f00-cf44-11eb-8133-17f8d3a84488.png)

**Comment by dcbroad3** [comment]
Thanks for the report! The site doesn't even have a login form, so it's definitely not phishing. Best guess it's that avg thinks the url is suspicious because of the state information zipped into it, but there may not be any way for me to flag to avg that it's safe. I'll look into it though.

**Comment by Liath0524** [comment]
I am getting an almost identical error with Avast Free Antivirus. I've been using the website for a while now, but Avast only started blocking it a couple days ago, also for "url:phishing". I am using Windows 10 with the Firefox browser. Whitelisting the site with Avast fixed it for me, but others might have the same issue.

**Comment by dcbroad3** [comment]
It is probable that they are using the same threat database or algorithm. I hope I can find a way to address the root cause.

**Comment by dcbroad3** [comment]
I submitted a false positive report to both AVG and Avast, fingers crossed.

**Comment by dcbroad3** [comment]
@B3lt3r @Liath0524 Could you please verify whether these warnings/errors still occur with AVG and Avast? I submitted false positive reports and as of this morning both companies have now said that they removed the false positive.

**Comment by B3lt3r** [comment]
> @B3lt3r @Liath0524 Could you please verify whether these warnings/errors still occur with AVG and Avast? I submitted false positive reports and as of this morning both companies have now said that they removed the false positive.

Confirmed! I've removed the exception from AVG and no alarms. Cool!

**Comment by Liath0524** [comment]
> 
> 
> @B3lt3r @Liath0524 Could you please verify whether these warnings/errors still occur with AVG and Avast? I submitted false positive reports and as of this morning both companies have now said that they removed the false positive.

All working again without the exception here too. Thanks!

**Comment by dcbroad3** [comment]
Thanks for following up! I will close this then.
