### ISSUE TITLE
Produce from 1 belt of hidden component => produce from 1 belt of product

### ISSUE THREAD

**Issue by jacquev6** [factoriolab/factorio-lab#525]
**Describe the bug**

On a recipe C produced from B, itself produced from A, selecting "Produce C from one belt of A", then ignoring B, changes the amount of C produced to one belt.

**To Reproduce**
1. Go to [https://factoriolab.github.io/list?z=eJwryNYyBMIctTTDeCct1zqP-MB4Ty2neHcQW61YS8u5LlOtzBgA3RMLQA__](https://factoriolab.github.io/list?z=eJwryNYyBMIctTTDeCct1zqP-MB4Ty2neHcQW61YS8u5LlOtzBgA3RMLQA__)
2. Observe 2016 "Copper cable" per minute
2. Click on "Copper plate" in the left column to ignore it
3. Observe 900 "Copper cable" per minute

**Expected behavior**

Hiding an intermediate component should not change the amount of final component: "Copper cable" should stay at 2016/m.

(Let's keep it real: this is a minor bug in an absolutely awesome tool, thanks a lot!)

**Comment by dcbroad3** [comment]
This is actually working as designed - since C is no longer part of the solution, the amount of C can no longer be used as a reference. Instead, it defaults to '1' to prevent an error. 

To create your desired behavior, the calc would have to determine which items to un-ignore when calculating the rates, which would not be trivial.

**Comment by jacquev6** [comment]
Understood, thanks!

Maybe there is something to fix in the UI to make that more explicit? In [this configuration](https://factoriolab.github.io/list?z=eJwryNYyBMIctcxcLUO1NMN4Jy3XOo.4wHhPLad4dxBbrVhLy7kuU63MGAAVoQyX) it's weird to see copper ore at the end of the first line.

**Comment by dcbroad3** [comment]
Would defaulting to '0' instead of '1' be more clear? This would make it more obvious the calculator is in an error state - defaulting to '1' make it at least *seem* like the calculator is still working as intended. Defaulting to '0' would indicate that something is broken at least.
