### ISSUE TITLE
`RangeError: Invalid array length` when using Krastorio 2

### ISSUE THREAD

**Issue by spalger** [factoriolab/factorio-lab#529]
**Describe the bug**
When using the `Krastorio 2` base set attempting to show the list view for any item fails with the error `RangeError: Invalid array length`

**To Reproduce**
1. Go to https://factoriolab.github.io/list?z=eJwrcC.WMlRL8lZLM4x3iveM91IrNtDS0nLSclYrMwYAewcHzQ__#z=eJwrUEvyVkszjHeK94z3Uis20NLSctJyViszBgBcUQa4
2. Make sure the list view is selected
3. Choose any item to show crafting instructions for

**Expected behavior**
It should show the breakdown in a list

**Screenshots**
![image](https://user-images.githubusercontent.com/1329312/123491523-ba8fdd80-d5cb-11eb-9a57-17ae7c91faaa.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Version: 1.26.67 

**Additional context**
Flow view works

**Comment by dcbroad3** [comment]
Thanks for the report! I'm having trouble reproducing this issue. Could you provide some extra info on what you're doing in step 3?

**Comment by yanalex981** [comment]
I'm getting it on the Dyson Sphere Program base set. I can reproduce it on Firefox and Chromium Edge. I've never used this calculator on Firefox so nothing should be cached. I use it all the time on Chromium Edge.

Reproduction on either browser:
Base set: Dyson Sphere Program
Enable the recipe "Graphene (advanced)"
Set product to Graphene

**Comment by react31** [comment]
I'm getting it on the vanilla factorio (all version exсept 0.16) for yellow science pack. Flow view works, but changing to list view show error. The list view only works if I disable the simplex solver.

**Comment by dcbroad3** [comment]
I still haven't been able to repro this, but I'd suggest turning off the Tree column, that's the most likely culprit for this error.

**Comment by dcbroad3** [comment]
Ok, I finally reproed this with yellow science. I'll look into it.

**Comment by spalger** [comment]
Yeah, apologies, I was consistently reproducing it with "Utility Tech Cards" in Krastorio 2, but would have sworn that I validated it was happening elsewhere... Maybe something else was happening. Thank y'all

**Comment by dcbroad3** [comment]
I have reverted the last update which seems to have caused this issue, I will look into fixing the root cause asap.
