### ISSUE TITLE
DSP gravity cubes

### ISSUE THREAD

**Issue by kimphoto808** [factoriolab/factorio-lab#536]
**Describe the bug**
it seems the DSP calculator needs to account that the game devs may have  nerfed the rate/min of 2.5 for gravity cubes. I was getting a slower rate compared to the other matrix labs while trying to make white science. I had to double the gravity labs to equal the same output rate as the other labs. maybe a game bug.. will see.   will need to figure how to test the gravity lab output in real time.

**Comment by dcbroad3** [comment]
The wiki data seems to match the data in the calculator:
![image](https://user-images.githubusercontent.com/8430702/123639151-e8546c80-d7ed-11eb-9f83-5f35f6720a06.png)

```json
    {
      "id": "g-matrix",
      "name": "Gravity matrix",
      "in": { "gravity-lens": 1, "quantum-processor": 1 },
      "out": { "g-matrix": 2 },
      "time": 24,
      "producers": ["lab"]
    },
```

However, as best I can tell, since it outputs 2 each time, it looks like it should be producing 5 per minute instead of 2.5 per minute.

**Comment by dcbroad3** [comment]
@kimphoto808 please follow up with more information or I may have to close this issue.

**Comment by kimphoto808** [comment]
Ya go ahead and close. I guess it could be just lag in how the cubes exit
the lab. It's just the gravity cubes are slow to output even if the
calculation is correct. Example is I built a mall using planetary towers to
feed the correct number of matrix labs to output 60 per min. Each set of
matrix labs feed into storage boxes of equal number. In theory all the
storage boxes should fill equally. But the gravity cubes took longer to
fill the boxes. The other labs dropped 1 per sec while the gravity was 2
per 2 sec. Same quantity but different spacing between output. Go figure..
Unless it that bug nilaus noticed 3 months ago on YouTube. That he lost
some items in his towers as a new load entered. Thus slowed down cube
production

**Comment by dcbroad3** [comment]
Well, if you have any further information that indicates it's a bug in this calculator I'm very open to investigating further, but based on what I can tell, everything seems to be correct as far as the recipe and what's in the DSP wiki.
Thanks for following up, in any case!
