### ISSUE TITLE
FactorioLab Website suddenly marked as malicious (AntiVirus Software)

### ISSUE THREAD

**Issue by Mirco1502** [factoriolab/factorio-lab#555]
Hello,

I'm using the calculator for DSP for approx 2 weeks now, with no problems. But suddenly (today) my AntiVirus Software (Avast) seals the page and prevents me from opening/enter it. Saying it's "malicious" and marked as phising website.

Any idea why or what's wrong?

Regards

**Comment by dcbroad3** [comment]
This happened once before, see issue #520. I should be able to submit a report to avast to have it fixed, though it's a little discouraging that this happened again so soon.

**Comment by Mirco1502** [comment]
I see and sorry to hear. That's indeed annoying. Thank you for your quick answer and I hope you can fix it again!

Regards

**Comment by dcbroad3** [comment]
I've raised this with Avast and AVG again, it seems like whatever they did last time may have been set to only last one month so hopefully they can address it more permanently this time or let me know what I can do to avoid being detected as a false positive.

**Comment by Mirco1502** [comment]
Hello,

Great, I hope they will mark it permanently. And thanks to you for this great tool!

Have a nice day!

Regards

**Comment by dcbroad3** [comment]
Thanks for closing but do you mind verifying that it's fixed now? AVG and Avast have both notified me that the issue has been resolved again.

**Comment by Mirco1502** [comment]
Oh wow, that was a misundertanding, I'm very sorry. Yes, I checked it and it's working again. With Avast Plugin active, the site/tool loads normally. No more malicious warning! :-)

Regards

**Comment by dcbroad3** [comment]
It's not a problem that you closed it, just wanted to verify it was actually fixed now 🙂. Thanks for checking!
