### ISSUE TITLE
Merge columns of flow (sankey) diagram

### ISSUE THREAD

**Issue by jxu** [factoriolab/factorio-lab#566]
![image](https://user-images.githubusercontent.com/7989982/127763886-bee6da35-1d02-488e-a4a1-832cbe79adb7.png)

For fun, I made a factory with one of its products being the spidertron. I'm not sure why raw fish gets its own column in the sankey diagram. I think all final products that aren't used in other recipes (no children) should be at the end column, all products that have children and no further descendants are in second to last column, etc.

**Comment by dcbroad3** [comment]
Well, I suppose I can make this an option, I think it just corresponds to the d3 sankey alignment options, described [here](https://github.com/d3/d3-sankey#alignments).

**Comment by jxu** [comment]
Wow that was fast. Yes, align right appears to be what the original kirkmcdonald calculator used. Thanks
