### ISSUE TITLE
Factoriolab appears to be quite broken at the moment

### ISSUE THREAD

**Issue by Schnobs** [factoriolab/factorio-lab#567]
It looks rather weird... though at second glance, it seems that merely the icons are off.

When selecting an item, the mouse-over text suggests that everything is still in it's usual place, but I'm shown (e.g.)big electric poles for transport belts, arithmetic combinators for cargo wagons, and so on. 

Picture: http://factorio.schnobs.de/factoriolab_20210801.png

**Comment by Schnobs** [comment]
....aaaand it appears to be fixed. I presume you just deployed a new version? Either that, or my umpteenth refresh somewhow worked better than the ones before. Thanks!

**Comment by dcbroad3** [comment]
The sprite sheet was changed, so yeah your browser must have gotten the new json data with the old png, which mixes things up. It shouldn't be necessary, but a shift+refresh should force it to get the new sprite sheet in the future. And no, I didn't deploy any fix 🙃
