### ISSUE TITLE
DSP: Add toggle to change between items/minute and items/second.

### ISSUE THREAD

**Issue by JamieRCHI** [factoriolab/factorio-lab#578]
Because there is a mod that displays the items/second, it would be nice to be able to toggle between items/minute and items/second.

**Comment by dcbroad3** [comment]
Hi Jamie, would this be different than this toggle?
![image](https://user-images.githubusercontent.com/8430702/128914951-fffb3b10-fc1c-472a-bd63-ac1093b84aff.png)

**Comment by JamieRCHI** [comment]
Sorry, Just found this out. Can this be removed?

**Comment by dcbroad3** [comment]
That's okay :smile: This seems to happen every few months, not sure how to make that dropdown more noticeable. If you have any ideas I'd be interested. I'll close out this issue.

**Comment by JamieRCHI** [comment]
I clicked the upper dropdown and didn't see the option. The dropdown on the next line down changes both. That was a bit confusing at first. 
And thanks for the quick response.
