### ISSUE TITLE
TypeError: Cannot read property 'beacon' of undefined

### ISSUE THREAD

**Issue by Cid-Dev** [factoriolab/factorio-lab#595]
When switching to the assembling machine 1 **in the settings** while there's an assembling machine 2 or 3 with a beacon wearing at least 1 module

[This build](https://factoriolab.github.io/list?z=eJwrcInQMjNQK3JJ1NLSMtTyqnNXSzOMd4r3iPdUKzMGAH0rCD4_) can be used to reproduce

Go to `settings`, then in the section `Factory` change the assembling machine preset to the 1

Then an exception will be caught and displayed :

> The application has encountered an error:
> 
> TypeError: Cannot read property 'beacon' of undefined
> 
> Click here to reset

This only occurs when the preset assembling is set to 2 or 3 and there's at least 1 beacon wearing module(s), without module there are no issues

When changing the assembling machine directly in the `List` (main tab) there are no problems (probably thanks to the fact the modules are removed in that case)

I don't know Angular, so I can't help you with a PR

**Comment by dcbroad3** [comment]
This is a good catch, thanks for the report. It's not properly removing the beacons from the recipes, you're right.
