### ISSUE TITLE
Industrial Revolution 2: no solution found

### ISSUE THREAD

**Issue by janfeitsma** [factoriolab/factorio-lab#621]
**Describe the bug**
When selecting the IR2 mod set, and when selecting an end-game product like space-science-pack,
then we get a popup error stating 'No solution found'.

**To Reproduce**
1. Open this link: https://factoriolab.github.io/list?p=space-science-pack*60&s=ir2&v=1
2. You should immediately see the 'No solution' popup.

**Expected behavior**
The popup should not occur.

**Additional context**
Workaround / solution suggestion:
* disable 8 scrapping recipes (they are clearly visible, light-green, in between hundreds of already disabled scrapping recipes)
* also disable sulphur-gas production from sulfur (to get rid of a water sink loop)

I am guessing somewhere underwater an explicit list is used for disabling the scrapping recipes.
If true, then to be future-proof, I would suggest to disable the recipes by pattern expansion 'scrap-*'.

**Comment by dcbroad3** [comment]
Default disabled recipes are in the data.json file for the mod data set, they are not automatically updated when the data set is updated. Thank you for the suggestions, I should be able to at least get this fixed, although setting it up to automatically update the disabled recipes would be more difficult.
