### ISSUE TITLE
Industrial Revolution 2: missing advanced factories in preset

### ISSUE THREAD

**Issue by janfeitsma** [factoriolab/factorio-lab#622]
**Describe the bug**
When selecting the 12-beacon preset, unexpectedly some mid-tier factories are used.
In particular: copper-mixer and electric-crusher.
Instead, advanced-mixer and advanced-crusher should be used.

**To Reproduce**
1. Go to https://factoriolab.github.io/list?p=glass-mix*60&s=ir2**3&v=1
2. Notice the use of copper-mixer and electric-crusher.

**Expected behavior**
Instead, advanced-mixer and advanced-crusher should be used.

**Comment by janfeitsma** [comment]
PS: great tool! It looks like you took the good ideas from Kirk and went beyond. The UI feels consistent, intuitive and responsive. Working around these minor issues was just quite easy.

(Now I gotta go figure out why my own simplex solver is giving different results, will not be so easy  :)...)

**Comment by dcbroad3** [comment]
Thanks for the suggestion! I don't play with a lot of these mods so I know the defaults aren't perfect for a lot of sets, I generally rely on players to let me know. It should be easy to get this updated (once I have time).
