### ISSUE TITLE
Alkene synthesis recipe is missing from Nullius mod

### ISSUE THREAD

**Issue by DRY411S** [factoriolab/factorio-lab#631]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dcbroad3** [comment]
![image](https://user-images.githubusercontent.com/8430702/140410036-e88988a6-a475-4505-9f03-003761a89dba.png)
![image](https://user-images.githubusercontent.com/8430702/140410048-09b98dc8-9991-47ab-b423-3d7459d2e1fa.png)

@DRY411S  These exist in the Nullius mod data set today. Are there other recipes that are missing?

**Comment by dcbroad3** [comment]
@DRY411S closing since I believe all the recipes are there.
