### ISSUE TITLE
Recipes of Dyson Sphere Program out of date

### ISSUE THREAD

**Issue by AtlasTang** [factoriolab/factorio-lab#638]
It looks DSP calculator hasn't been updated for a while. Some recipes are out of date now, such as solar panel.
Can anyone help to update the recipes?

**Comment by dcbroad3** [comment]
I should be able to look into this next week.

**Comment by AtlasTang** [comment]
> I should be able to look into this next week.

I realized I went into an old page of DSP calculator.
The new page (https://factoriolab.github.io/dsp) looks working well.
I think this issue should be closed.

**Comment by dcbroad3** [comment]
Were you using shadowtheage's version by chance? I'll close the issue then 🙂

**Comment by AtlasTang** [comment]
> Were you using shadowtheage's version by chance? I'll close the issue then 🙂

yep.
