### ISSUE TITLE
Only works in incognito mode

### ISSUE THREAD

**Issue by Trequetrum** [factoriolab/factorio-lab#640]
Once I've loaded up one of the three calculators, I will forever be stuck being re-directed to that calculator. Wiping cookies, switching browsers, switching computers, opening a browser in incognito mode fixes the problem for a hot second. Changing my settings to disallow FactorioLab to store anything in cookies breaks the site entirely. So I'm stuck using workarounds.

**Comment by dcbroad3** [comment]
@Trequetrum If you are able to discuss in the FactorioLab Discord server that might be helpful.

1. Have you tried using the "Game" dropdown in the Settings menu?
![image](https://user-images.githubusercontent.com/8430702/142473761-4e26b2bf-6ca4-42bf-b097-2b245e69cbc0.png)

2. I am assuming you mainly mean that the links at the top of the page do not work to redirect you to the other game calculators?

3. Are you using Chrome? Mobile or desktop?

4. If on desktop, could you open the browser developer console and check if there are any errors there? (Right click, "Inspect", and check for anything in the Console)

I ask because I am not able to duplicate this issue in Firefox or Chrome. I admit I have occasionally seen it get stuck in one game and the links at the top do not work, but it always works after refreshing the page, so I'm not sure what is unique about your issue.

**Comment by Trequetrum** [comment]
Hey, 

1. I hadn't tried that, that seems to work and solves my problem. Though I'm a bit surprised that the settings menu and the links at the top of the page aren't handled the same way! Does one reload the page and the other routes SPA-style?
2. Exactly, yes.
3. I'm using Firefox with GalliumOS (desktop).
4. The console does say: _Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=G-TFR5Z43GPH”._

**Comment by dcbroad3** [comment]
The links at the top are actual links, anchor or <a> tags, that route to the different game calculators. I'm also interested if you ctrl+click one of those links to open it in a new tab, does that work or no?
The dropdown in the Settings menu actually changes the game internally without reloading everything (hence a bit more reliable).
It seems that the application is not detecting the URL change when you click on the link. I'm curious, what does the address bar show when you click on the links, does it change or not?
That message in the console is not relevant to this issue. 

Previously those links worked a bit differently, they would set the URL, wait 100 - 250 ms, and then force the page to reload. I think that method might be more reliable and I might have to switch back to it to make it work in your case. I'll set that up in the staging environment at some point and you can tell me whether the links work there. (Not sure when that will be with the Thanksgiving holiday coming up though)

**Comment by Trequetrum** [comment]
I can restart my computer, but if I haven't cleared my cookies, the issue persists. Opening in a new tab doesn't make a difference. Copy and pasting the URL for a different calculator doesn't make a difference either. It just returns me to the last recipe I had open on the last calculator that I used, it even changes the URL.

Right now, for example, if I write in any valid address, I get redirected to https://factoriolab.github.io/list?p=supercomputer*60&s=dsp&v=1

If, however, I navigate to https://factoriolab.github.io/list?p=error, then I get an error message "The application has encountered an error: TypeError: t is undefined" and then the links at the top will work again. Until I've loaded a recipe in any of the 3 calculators. 

No errors in the dev console throughout.

**Comment by dcbroad3** [comment]
@Trequetrum I know it's been a minute, but if you have a chance, could you please try this out at https://factoriolab.github.io/staging. If you can open the developer tools and check the console, it should log some information about the `location` that would be helpful in debugging this. Specifically what I would like you to try is to navigate to: 
https://factoriolab.github.io/staging/list?p=wooden-chest*1&v=1 (Factorio Calculator)
Then, navigate to:
https://factoriolab.github.io/staging/list?p=iron-ore*1&s=dsp&v=1 (DSP Calculator)

On the second navigation, open the console and let me know what is logged. I am not able to reproduce this problem so this may be a bit tough to fix. The application is supposed to check whether you have a state in the URL before loading any saved state from local storage. My only guess is on your system that check fails for some reason, and the application thinks you don't have any state in the URL when you actually do. I've added a lot of debug statements in that area to see if I can determine why that check fails.

**Comment by Trequetrum** [comment]
Hey @dcbroad3, I'm not seeing this bug anymore. I've tried to re-create the exact conditions that caused it before, though I can't be sure. I'd originality navigated via a bookmark, though I've since deleted that bookmark.

**Comment by dcbroad3** [comment]
Thanks for the update. Do you mean you're not seeing the bug even at https://factoriolab.github.io, or not seeing the bug just at the staging website I pointed to?

**Comment by dcbroad3** [comment]
@Trequetrum can you confirm, you don't see this issue at all any more? Should this issue be closed?

**Comment by Trequetrum** [comment]
I'm not seeing it at either address. This issue should be closed (I'll re-open if it happens again and can be consistently reproduced). 

Thanks for your time/effort!

**Comment by dcbroad3** [comment]
Thanks for following up!
