### ISSUE TITLE
recipes info error in satisfactory tools

### ISSUE THREAD

**Issue by Ronneraz** [factoriolab/factorio-lab#643]
recipes in tools
![无标题](https://user-images.githubusercontent.com/32998616/145133797-322aa869-d5cb-4b2d-9e21-b9ddc10a6f03.png)
recipes in game
![无标题2](https://user-images.githubusercontent.com/32998616/145133803-de1d89c3-0aa2-4a20-a5a6-3bb128308cf4.png)

**Comment by dcbroad3** [comment]
Thanks for the report, I'll see if I can get this fixed soon.
