### ISSUE TITLE
Incorrect Calculations

### ISSUE THREAD

**Issue by John-osu** [factoriolab/factorio-lab#654]
When calculating input items for the selected recipe, the given result is incorrect.

Example:
Using Blue Circuits as an example:
1) Select 1 factory with 4 prod3 and 8 s3 beacons.
2) The input shown for Green Circuits per second is 18.48. (15.4 not counting red circuits).

The input needed per second (ignoring red circuits) is 11 per second in reality.

If the final step is modified to include the prod3 modules, the calculation is correct. 
The full calculation should include all modules given in the header.

**Screenshots**
![image](https://user-images.githubusercontent.com/75799007/146998643-e9befe2b-89f3-40eb-ac26-92df959fe7c1.png)
![image](https://user-images.githubusercontent.com/75799007/146998825-5e040c2d-e77b-4b59-9af1-70f75e6b29c5.png)

**Comment by dcbroad3** [comment]
@John-osu This is just a misunderstanding of what the factory settings in the products tab do. They are only used to calculate a rate of items, any productivity is effectively ignored. What you really want to do is set the beacons and modules in the list only. 
The settings at the top are intended mainly for situations like a beaconed column of furnaces where a couple have less beacons than the rest. This can then be used to determine how much product the furnace column can produce, although it kind of invalidates the factory settings in the list at that point.

**Comment by dcbroad3** [comment]
I really need to improve on the ui there because this is more often a point of confusion than it is useful.
