### ISSUE TITLE
Satisfactory Calculator Incorrect Calculations bug

### ISSUE THREAD

**Issue by happymy** [factoriolab/factorio-lab#656]
6 Uranium Fuel Rod /min in 15 nuclear power plant(overclock 250%) ->300 Uraniumwaste /min.
NOT 12 nuclear power plant(overclock 250%) .

correct:
100%, Uranium Fuel Rod 0.2 /min+300 water /min->10 Uraniumwaste /min,out 2500MW 
150%, Uranium Fuel Rod 0.27 /min+408 water /min->13.59 Uraniumwaste /min,out 3750MW 
200%, Uranium Fuel Rod 0.34 /min+507 water /min->16.89 Uraniumwaste /min,out 5000MW 
250%, Uranium Fuel Rod 0.4 /min+600 water /min->20 Uraniumwaste /min,out 6250MW

**Comment by dcbroad3** [comment]
> When overclocked, Nuclear Power Plants scale differently compared to any other generator buildings; their power exponent is 1/1.321928 instead of 1/1.3. Therefore, at 250% clock speed, they operate 2.00000009951 times as fast, for resource input, waste output, and power production. 

The calculator doesn't currently account for this, should be fixable.
