### ISSUE TITLE
Factorio Calc - Mod: Krastorio - Simplex Solver only uses Advanced Assembler for Copper Wire Ingredient

### ISSUE THREAD

**Issue by guywbailey** [factoriolab/factorio-lab#659]
Using Factorio Calculator with Mod Set Krastorio, Simplex Solver only uses Advanced Assembler for Copper Wire Ingredient

Steps:
1. Select the Factorio Calculator
2. Change mod set to Krastorio 2
3. Set Factory - Assembler to Assembler 2
4. Set Advanced - Simplex Solver to Enabled
5. Add a product: Advanced Circuits
6. Observe the Copper Wire step. Note it is using 'Advanced Assembler'

Expected Behavior: I would expect all steps to use 'Assembler 2'

Tests:

1. I tried changing 'Factory - Assembler'  to Assembler 1, Assembler 2, etc to see if this affects copper wire. No effect.
2. I experimented with changing recipe sets. No effect.
3. Next, I checked to see if this behavior happened with Vanilla. It did not.
4. Next, I checked to see if the happened with mod set: Krastorio 2 + SE. It did not.

URL for Solar Panel that also shows this:

https://bit.ly/343e4U2

Screen shot shows Assembler 2 selected but Adv Assembler for Copper Wire.

![Krastorio2_copperwire_simplex](https://user-images.githubusercontent.com/1850831/148247201-198d936f-2806-4c00-9a2c-19b63d19d2e4.png)

**Comment by dcbroad3** [comment]
If you expand that step and look at the recipes tab you can see there are two recipes for copper cable. Both are enabled by default and simplex chooses the advanced recipe, which requires an advanced assembler. The simplex solver doesn't care about your factory preferences when choosing what recipes to use. 
That being said, the advanced recipe should probably be disabled by default here.

**Comment by guywbailey** [comment]
Thx!

**Comment by dcbroad3** [comment]
Well, for what it's worth, I checked and the advanced recipe is actually disabled by default, so somehow it got enabled in your case. 
Found another bug in the data while checking, though, so I'll publish that fix.
