### ISSUE TITLE
Satisfactory - Steel rotor problem 

### ISSUE THREAD

**Issue by malyBobr** [factoriolab/factorio-lab#666]
**Describe the bug**
If calculate 1 steel rotor price is OK 2 steel pipe and 6 wire.
( https://factoriolab.github.io/list?z=eJwFwcFywWAAhdG3ySILI8pg6d5fopgq1dTYJWgVbUXJmC6-Z-85Z7XiJCrz6DeOGzRp06WPEjRAAaVohMZoimZogZboFeVohQpUoh16R3v0jX5QhS6oRnfcwE2c4Dbu4C7u4QEOOMNP-Bkv8AvO8Rte4TUu8Bbv8Sf-whW-4huuCSakhIwwYkjGIxOmzJizpGDDlh0fHDhyouLClRs1d.6i-uEf361WiA__ )

If calculate 1 adaptive control unit price is bad 3 steel pipe and 8 wire.
( https://factoriolab.github.io/list?z=eJwFwctOwlAARdG.6aADQiMGHPacC0VsQBFKp0Vegg-K0DQO9rez1jmNk2hdRH9x3KFLjz5PKEEpCmiExmiCcjRDc7RAS1SgElVojbZohw7oB.2iGl1Qg1rcwV2c4B5-xH08wCkOOMNT.Irn-B0XeIVLXOENPuBP.I1rfMU33BBMGBEywpghGc-8kDPjjQUVH2zYsufIiS9qLly50dDyHzUPd7giVTo_ )

**Screenshots**
OK:
![obrazek](https://user-images.githubusercontent.com/82827348/149666938-7319a9a7-dded-4e24-b08e-9e220d7bdf4c.png)

BAD:
![obrazek](https://user-images.githubusercontent.com/82827348/149666960-0d1ca1ed-9ead-45b3-8678-fc2b7c684b94.png)

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Firefox
 - Version: Actual

**Comment by dcbroad3** [comment]
I'm not clear on the issue here. It appears you are comparing the recipe for the **Rotor** with the recipe for the **Stator**. Those are two separate items with two separate recipes.

**Comment by malyBobr** [comment]
Hello,
I have to apologize, I made mistake in my calculations. Now is everything in order, I am sorry for the ticket.
