### ISSUE TITLE
MSP -  30 New Science Packs

### ISSUE THREAD

**Issue by aanogueira99** [factoriolab/factorio-lab#668]
**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factorio-lab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.

**What mod set are you requesting?**
E.G. "Bobs and Angels", "Pyanodons", "Seablock", etc.

**Is this mod set compatible with the latest version of Factorio?"
Yes or no. If no, please list the last version that it is compatible with.

**What mods are included in this mod set?**
E.G. list all the distinct mods that should be included from the mod portal.

**Comment by dcbroad3** [comment]
So to clarify, the calculator already supports "MoreScience" by lovely_santa. "MSP - 30 new Science Packs" is, according to its author, just the same mod "I just increased the factorio version and added a fix mod". 

Do you still think it's necessary to add support for this one? It seems far less popular (1711 downloads vs 21728 for "More Science")

**Comment by dcbroad3** [comment]
Closing this issue - feel free to comment later if you would still like this to be added.
