### ISSUE TITLE
Higher level electric miners for Bob's Mods?

### ISSUE THREAD

**Issue by TatianaKat** [factoriolab/factorio-lab#672]
Hi there!

Apologies in advance if this has been suggested already, but it'd be great to see the higher tier Electric Miners from Bob's Mining mod added to the calculator. Doesn't seem to be there already, unless I've missed it!

**Comment by dcbroad3** [comment]
This is not the first time this has been reported (and fixed):
https://github.com/factoriolab/factorio-lab/issues/478

I'm not sure how they got removed yet again, I will look into it.
