### ISSUE TITLE
[DSP] Simplex solver avoids using Gas/Ice Giant mining to produce hydrogen, outputs inbalanced solutions instead

### ISSUE THREAD

**Issue by C0ldSn4p** [factoriolab/factorio-lab#679]
In DSP hydrogen is produced as a byproduct of some recipes and used in usually greater quantities than what is obtained this way when producing end-game products, i.e. universe matrix (final "white" science) and small carrier rockets (main component to build the Dyson Sphere)

The player is expected to use Orbital Collectors to passively mine Gas and Ice Giants planets, which directly produces hydrogen that can be used to balance the production lines.

The simplex solver avoids using this method, instead it tries to use the recipes having hydrogen as byproduct to balance it, resulting in an excess of the main product of these recipes which would clog up the factory and is also a much less practical way to obtain the required hydrogen

**To Reproduce**
1. Go to https://factoriolab.github.io and go to the DSP calculator
2. From the default 14 enabled recipes, add the 2 giant mining recipes
3. Enable the simplex solver
4. Ask to produce 1 universe matrix (white cube)
5. See error that excess anti-mater is expected
6. If you look at the hydrogen you'll see that most of it is produced using Mass Energy Storage instead of orbital mining of Ice or Gas Giants

For example: https://factoriolab.github.io/list?z=eJwrcKrSMjNQS.JQK9bScvKrcwqtc4qoc8quc8qpc3arc3avC6iLrEupy66rVCszBgBbRw.T#hydrogen

**Expected behavior**
The solver should balance the hydrogen with the orbital mining. Note that orbital mining from an Gas/Ice Giant does not need to output the same ratio of products: an orbital collector could be full of the secondary product and still mine hydrogen

**Screenshots**

https://factoriolab.github.io/list?z=eJwrcKrSMjNQS.JQK9bScvKrcwqtc4qoc8quc8qpc3arc3avC6iLrEupy66rVCszBgBbRw.T#hydrogen

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
I suspect that either the simplex calculator does not separate the orbital collector recipes' outputs (so it assumes that using it would result in an imbalance in fire ice or deuterium), or that the weight on the two Orbital Collector recipes are wrong, making the simplex favor an imbalanced solution over using them

**Comment by BlackestDawn** [comment]
I'd say that on a technical level it's actually a bit worse than what you have presented, like [this one](https://factoriolab.github.io/list?z=eJwrcCrSMjOITwYR.kBCLclDLdMpS0vLKd4cRJgBCbUipzItLXe1NEMtt3jn-GS1Yi0tZzctZy0trVAtZOCmVmYMAFPrE6Y_).

Simply speaking, having all recipes except x-ray cracking enabled suggest I create critical photons and split them to cover remaining hydrogen needs even though I don't use critical photons nor antimatter in any capacity.

**Comment by dcbroad3** [comment]
The gas giant recipes are currently set to have a higher cost, it sounds like in general that just shouldn't be the case. My understanding in the past was that mining gas giants was rare and difficult to set up, but if it's the standard way to get hydrogen in the late game, then the cost should reflect that.

**Comment by C0ldSn4p** [comment]
@dcbroad3 exactly. One way to adapt this would either to have a toggle or to link the weight of the gas giant recipes with the assembly machine used for example (if you are using mk1 machine you are probably in the early game, whereas mk3 requires you to be at a point where orbital mining is not too hard)

**Comment by BlackestDawn** [comment]
I never got the impression that mining gas giants was ever rare. Sure it might be a pain to setup but if you've automated every step you came across along the way it's essentially just a bit of time waiting for them to be produced.

If the weight on orbitals will be changeable/dynamic then I feel it must be user configurable. Mainly because you can unlock orbitals without unlocking mk2 assemblers. Sure, have the defaults be based on configured assembler tier but let me set it to match my exact situation.

**Comment by dcbroad3** [comment]
To be fair, the cost is already configurable today via the Matrix tab. I'm treating this just as a request to change the defaults.

**Comment by C0ldSn4p** [comment]
Oh I did not know you could change the default in the matrix tab.

While you are at it I would increase the cost of the Mass Energy Conversion recipe (the one producing antimatter from critical photon) a bit since this is late game and the only way to produce antimatter anyway so the solver should use it to produce just the right amount of required antimatter and never use it to produce excess of it

**Comment by BlackestDawn** [comment]
Having slept on this I feel that there is some form of disconnect here. Isn't the primary purpose of being able to enable and disable specific recipes/sources to indicate what of those are available and/or what you actually want to use? If so then shouldn't the weight effectively only reflect "cost of operation" (so to speak) and efficiency of the recipe itself, not how rare/difficult it would be to acquire the tech or how rare/difficult its setup would be?

**Comment by dcbroad3** [comment]
@BlackestDawn this seems like a fair point. If you aren't interested in using gas giant mining as part of your solution, that's easier to accomplish by disabling the recipe than changing the cost. Therefore the cost itself should be reasonably low so that gas giant mining is a preferred solution if it is enabled.
