### ISSUE TITLE
Critical Photons from Proliferated Graviton Lense

### ISSUE THREAD

**Issue by MrJoshua023** [factoriolab/factorio-lab#683]
Currently the Critical Photon production does not take into account any Proliferation
It would be helpful to add an option to set proliferation level.  

When calculating the achievement of 1 blue belt universe science.  It states I need 240 Ray Receivers, with proliferation, this is only 60.

**Comment by MrJoshua023** [comment]
Fast work!  However this particular issue doesn't show a change.
![image](https://user-images.githubusercontent.com/62954862/153027947-6244ef48-f44e-4068-a085-1c4f69dd0c1f.png)

**Comment by dcbroad3** [comment]
@MrJoshua023 it looks like you are using the recipe without graviton lens in that image. I would make sure the recipe with graviton lens is enabled, and you might need to disable the other recipe as well to force it to use it. 
Since the recipe without a lens takes no inputs, I assumed that one cannot be proliferated.

**Comment by MrJoshua023** [comment]
Thanks, just figured out how to set the default recipe on an individual item.  However, the math still doesn't look right for proliferated.  I assume its corrected for plain graviton lenses tho.
![image](https://user-images.githubusercontent.com/62954862/153032347-2394bf6f-9575-4778-aa12-2533755f6787.png)

![image](https://user-images.githubusercontent.com/62954862/153032755-05e29da6-36d0-402e-93f7-5fd4664d9bc7.png)
1440 per min / 24 per minute = 60 ray receivers.

**Comment by dcbroad3** [comment]
Is that using the speed bonus from the proliferated lens? With the speed bonus the numbers match up, it's with 'extra products' that it seems off. Are you even able to choose whether to use extra products or speed bonus in this case?

**Comment by dcbroad3** [comment]
Actually the graviton lens consumption lines up with using extra products. I wonder if the recipe is just wrong in my data. Do the numbers match up when not proliferated?

**Comment by MrJoshua023** [comment]
Give me a few, I'm gonna set up a few receivers and let them get to 100% to get you all possible options.

**Comment by MrJoshua023** [comment]
Ok, here we go.
![image](https://user-images.githubusercontent.com/62954862/153040130-298fc0d6-c2e0-49dc-81f4-71523a9eb06c.png)

**Comment by MrJoshua023** [comment]
Correct.  Here is also lvl1 and lvl2 proliferated added to the picture now.

![image](https://user-images.githubusercontent.com/62954862/153042874-38a506a6-f81b-4410-b651-edbba3950295.png)

**Comment by dcbroad3** [comment]
Thank you for taking the time to put these together. I'm reopening the issue and I'll try to get this sorted out.

**Comment by dcbroad3** [comment]
So it seems straightforward, and to me it seems like a bug. 

1. Only production speedup is allowed, not extra products. The output corresponds to the production speedup bonus level exactly. 
2. Production speedup, in this case, only increases the output, not the speed at which the ray receiver uses graviton lenses. Hence it uses 0.1/minute no matter how much the production speedup is. This is highly unusual. 

I can only assume that the game does not treat the graviton lenses as a true input to the recipe, and instead as a steady recurring cost of running the factory. This is comparable to 'burner' factories that consume a steady supply of fuel no matter what the 'speed' of the recipe is. 

So.. that's what I'll do. I'll treat the lenses as a fuel. Will take a bit of tweaking but think I'm close.

**Comment by MrJoshua023** [comment]
I definitely see that, it does look like it treats it as a fuel source.  Thanks for looking into it!
