### ISSUE TITLE
Setting to specify items as "base ingredient"

### ISSUE THREAD

**Issue by MarcusTL12** [factoriolab/factorio-lab#687]
When I want to get the ratios of a rather complex recipe, it would be nice to be able to specify which items are the "base items" that are not expanded further in the production tree. For example when setting up production of blue circuits, I do not really care about how many smelters I need for the Iron, or the whole Oil production mess. It would then be nice to be able to for example specify green circuits, Iron/copper plates and sulfuric acid as base resources, so that it does not tell me how to produce them, only how much I need. The option of which recipes to ignore does this somewhat, with some recipes, but not fully.

**Comment by dcbroad3** [comment]
Have you tried ignoring specific items? E.g. if you click on the electronic circuit icon in the list, the calculator will tell you how many electronic circuits you need, while ignoring how many assemblers you need and how much copper wire/iron plates and everything down that chain.

**Comment by dcbroad3** [comment]
Here's an example with blue circuits:
https://factoriolab.github.io/list?z=eJwrcPbVMjNQy3TSMow3BGIXdy1DtWItI7UyYwBfPAax

**Comment by MarcusTL12** [comment]
Ah, turns out that is *exactly* what I was looking for. Turns out the problem was me being blind. Thank you very much!

**Comment by dcbroad3** [comment]
No problem! This is one of the most commonly overlooked features, and I really need to find a way to make it more obvious.
