### ISSUE TITLE
Recipe details in column

### ISSUE THREAD

**Issue by ggrnd0** [factoriolab/factorio-lab#690]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add column with recipe details along with hover tooltip

**Describe alternatives you've considered**

**Additional context**

**Comment by dcbroad3** [comment]
Could you go into a little more detail on what this would look like? There should be a recipe icon in the factory column with a hover tooltip already, if that's what you mean.

**Comment by dcbroad3** [comment]
Closing, if you can provide additional context I can reopen the issue.
