### ISSUE TITLE
Ficsit Farming mod for Satisfactory

### ISSUE THREAD

**Issue by envy2000** [factoriolab/factorio-lab#698]
**Have you checked whether this mod or set of mods has already been requested?**
[Check here](https://github.com/factoriolab/factorio-lab/issues?q=is%3Aopen+is%3Aissue+label%3A%22mod+support%22)
If you find the mod you're looking for, add a "thumbs-up" reaction or a comment to the issue.
Yes

**What mod set are you requesting?**
E.G. "Bobs and Angels", "Pyanodons", "Seablock", etc.
I am requesting support for mods in the Satisfactory calculator, specifically, the Ficsit Farming mod

**Is this mod set compatible with the latest version of Factorio?"
Yes or no. If no, please list the last version that it is compatible with.
Ficsit Farming is compatible with the latest versions of both the experimental and the early access branches of Satisfactory

**What mods are included in this mod set?**
E.G. list all the distinct mods that should be included from the mod portal.
Ficsit Farming

**Comment by dcbroad3** [comment]
Is there a wiki or something where I can see all the items and recipes that are added as part of this mod? I don't own Satisfactory, the current data set was crafted from the wiki, so without a website documenting the data it would be very difficult to construct this.

**Comment by dcbroad3** [comment]
Closing this issue - if there is a resource I can use to build this data set, I'm open to reconsidering, but I do not own Satisfactory and do not intend to build mod data sets for Satisfactory purely based on in-game screenshots / info.
