### ISSUE TITLE
Proliferator calculations incorrect

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#710]
The "proliferator self spray" is not correct. Looks like it's calculated recursively and loops once (items/sprays_per_proliferator + items/sprays_per_proliferator^2). Instead, it should calculate using sprays per proliferator (after the bonus productivity) minus 1. so, [required proliferator] = [things being sprayed]/( [sprays per proliferator] - 1). Also, you're using the exact productivity for sprays (13.5 for MK1 sprayed with MK1, and 28.8 for MK2 sprayed with MK2) even though the game rounds down. With MK3 and self spray, each proliferator has 75 sprays, but one of those has to be used to replace itself, so a net spray of 74 each. MK1 is still 12, MK2 is 27.

Reported by zomg in Discord

**Comment by lildadou** [comment]
I built a complex to produce 3 belt mk2 of proliferator mk2 self-proliferated (so sprayed with mk2). The [solution given](https://factoriolab.github.io/list?z=eJwrcPbVMjbWMtbS0nJTS.JQy4zSMox3sgQRelqGakXhIJYxkKjUMogHqgUpSwMKxUfGu6oVA7lOWo5acOCmVmYJAENGE8A_&v=9) is 33 mk2 assembler for an expected spray consumption of 220/m. In practice, the total output calculated is the same, but I obtained a consumption of ~290/m by the sprayers.

In fact, the calculation gives 8316/m to be sprayed, i.e. 288.75/m proliferator (28.8 spray per proliferator).
