### ISSUE TITLE
Decimal separator is displayed as comma instead of dot for certain languages

### ISSUE THREAD

**Issue by stevenwdv** [factoriolab/factorio-lab#731]
**Describe the bug**
Since the internationalization updates FactorioLab displays a comma instead of a dot for the decimal separator for me, e.g. `1,5` instead of `1.5`.

**To Reproduce**
1. You probably need to set your browser language to one that uses a comma for the decimal separator, e.g. Dutch. Changing the number format used by the OS may also be necessary, depending on your browser settings.
2. Go to '[1.5 wooden chests](https://factoriolab.github.io/list?p=wooden-chest*1.5&v=1)'. Note that the FactorioLab language is English (although the issue is also present for other languages).
4. Observe how 'Items/m' and 'Belts' are displayed as `1,5` and `0,1` respectively, while input boxes like the one on the top still use dots. Also note that if you put in 1000 Items/m it may render this as `1.000` (so also a wrong thousands separator).

**Expected behavior**
As the rest of FactorioLab is English, the numbers should use dots as decimal separator.

**Screenshots**
![decimal separator](https://user-images.githubusercontent.com/27223270/167219472-e8f9ae84-715e-4574-91c2-14f2071fd18c.png)
![thousands separator](https://user-images.githubusercontent.com/27223270/167219574-370645d8-ffba-4dfb-9eef-126fadcfff01.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 101.0b3

**Comment by dcbroad3** [comment]
This was actually done separately from the language selector, just to honor the user locale when displaying numbers. However seeing as the inputs do still display as English locale it is indeed confusing. I'll either revert those changes or see whether I can also localize the inputs, though that does seem much more difficult.

**Comment by stevenwdv** [comment]
Ah ok. Personally, I'd prefer having English-style numbers - makes more sense when that's the site language and otherwise there's no way to know what a site wants as input format anymore. Also, it's easier to copy to a calculator that expects dots, although the thousands separators screw that up anyway; having the thousands separators but not copying them would be ideal, but it doesn't matter that much I guess.

**Comment by dcbroad3** [comment]
It seems like yet another case where I need to have options in settings, haha. That or I will just revert the change, since honestly this wasn't a change that was ever asked for.
