### ISSUE TITLE
Space science pack calculations are incorrect

### ISSUE THREAD

**Issue by TitoRigatoni** [factoriolab/factorio-lab#738]
**Describe the bug**
The crafting rate for the rocket silo does not account for the time taken by the launch animation. The calculator assumes the rocket silo constantly makes parts, but it only crafts parts about 20 seconds out of every minute.

The actual effective crafting speed of the rocket silo is 0.698, and the calculator should reflect this.

**To Reproduce**
1. Select Space Science Pack, produce from 1 Rocket Silo
2. Select four Prod3 modules in the silo, 20 Speed3 in beacons
3. Observe production per minute 1404.6

**Expected behavior**
Actual production of Space Science Pack is about 981 per minute. The calculator should accurately display this number.

**Comment by dcbroad3** [comment]
I assume you mean 20 beacons with two Speed3 modules each.

**Comment by TitoRigatoni** [comment]
https://factoriolab.github.io/list?z=eJwrcC7VMtQyVsv01zJUK3Iu0NJyqwNDLSMDAy3POs9451wtLS0LEFOtWMtICwS8U9XKjAHWHw-G

**Comment by dcbroad3** [comment]
@TitoRigatoni it looks like in your link you had actually specified 200 beacons 🙃
The field is cut off so it looks like 20

**Comment by TitoRigatoni** [comment]
omg now I feel like an idiot :-D
