### ISSUE TITLE
Show where the output of a factory goes

### ISSUE THREAD

**Issue by rstarkov** [factoriolab/factorio-lab#74]
Sometimes I need to know where the outputs of a factory go. It's useful to see both which other recipes take the current recipe as inputs, and also in what quantity. In Kirk McDonald's calculator I can get this info from the Visualise graph, but it's not optimal for this, especially if I need to see exact numbers.

(later edit) One possible approach to this is something like:

![image](https://user-images.githubusercontent.com/149002/82251572-566d0580-9945-11ea-8c33-e3ec75c63e65.png)

**Comment by dcbroad3** [comment]
Trying to picture this. What I'm considering is that if I didn't combine steps, and instead always showed separate input steps for each recipe, would that meet your needs? E.G.

- Red Science
    - Gears
      - Iron Plates
        - Iron Ore
    - Copper Plates
      - Copper Ore
- Green Circuits
  - Iron Plates
    - Iron Ore
  - Copper Wire
    - Copper Plates
      - Copper Ore

**Comment by rstarkov** [comment]
I'm not entirely sure what you are proposing, but using your example, I'd like to be able to look at Iron Plates and see that 30% (X per min) of them go into Gears, 50% (Y per min) into Green Circuits, etc.

**Comment by dcbroad3** [comment]
OK, that makes a lot of sense. Basically it seems like what I was proposing is a "Production" hierarchy, what you're looking for is a "Consumption" hierarchy. 
I've been giving this some thought and I'd like to experiment with using a sunburst diagram to show both the consumption and production hierarchies. 
The analog using the tiered list above would be to flip it, like:

- Copper Ore
   - Copper Plates
      - Copper Wire
         - Green Circuits
      - Red Science
- Iron Ore
   - Iron Plates
     - Gears
        - Red Science
     - Green Circuits

**Comment by rstarkov** [comment]
I suppose that could work. Would you create a separate tab for that?

Alternatively, it could be displayed in the tooltip that pops up when you hover an item, where it shows the recipe.

For example, consider [this factory](https://factoriolab.github.io/#eJwrsDU0MbIysDI0MNAxNDGGs0whLABrNQZu) - it's just 100/min of red, green and blue sci.

The popup might look something like this:

![image](https://user-images.githubusercontent.com/149002/82251572-566d0580-9945-11ea-8c33-e3ec75c63e65.png)

The "input" numbers can already be seen by using the "open in new tab" feature (although it's not entirely obvious which inputs are the direct recipe constituents) but the output numbers are simply not available anywhere.

**Comment by dcbroad3** [comment]
It might end up being a bit too much for a tooltip, especially when there might be five or so rows of inputs/outputs, and I'd probably also like to include the # of factories for each row, but some way to get that information in this view would definitely be nice. I might toy with a way to expand or select/inspect a row. Generally speaking I'd like to do something very similar to your example though.

**Comment by dcbroad3** [comment]
@rstarkov This feature is live! It's exposed via an 'expand' button rather than the tooltip, but I hope this is basically what you were asking for. 

![image](https://user-images.githubusercontent.com/8430702/83174762-d97e2080-a0e8-11ea-9992-69559dfe421c.png)

**Comment by SteveS8** [comment]
I love this feature. Now I can easily see for example how many belts of iron I need for steel versus the rest :)
