### ISSUE TITLE
not 32px icons

### ISSUE THREAD

**Issue by hhrhhr** [factoriolab/factorio-lab#89]
from changlog:
```
Version 0.18.27
Graphics
New high resolution icons for all items.
New sprites for some equipment grid items.

```
but:
![64_err1](https://user-images.githubusercontent.com/966048/82925691-bd626e00-9f86-11ea-80ec-39da83ddef36.png)
![64_err2](https://user-images.githubusercontent.com/966048/82925696-bfc4c800-9f86-11ea-8424-7d48ebac89ae.png)

**Comment by dcbroad3** [comment]
Man you are fast. 
Was going to write up an issue for updating to the new icons but I'll just use this one.

**Comment by dcbroad3** [comment]
@hhrhhr One issue with your generator: It looks like it doesn't currently include the information required for the infinite researches included in this app.

**Comment by hhrhhr** [comment]
Yes, there is such a thing.
I'm still trying to understand how to uniquely identify "endless technologies" in order to automatically include them in "recipes".
authors of different mods show an enviable fantasy when they add their technology ;)

**Comment by dcbroad3** [comment]
Updated icons and updated code to handle icon sizes should be merged soon. 
There will be no more icons.scss. Icons will be declared as an array in data.json, with four fields:

- `id` which is either the item id or recipe id
- `position` which is the css `background-position` value to use for the sprite
- `size` which assumes 32px if not defined but should handle 64px and 128px values using `size-64` and `size-128` flags
- `file` which is intended to help with mods (we'll see whether it actually does), this lets you point to a different sprite sheet so you could theoretically have different sheets, the value of this field is rendered in the icon as `background-image: url("{file}");`

**Comment by hhrhhr** [comment]
Сan you see what is wrong with this exported data.json?

The zip archive contains data.json and related textures. Аs I understand it, some element does not have the "category" parameter, but I cannot find it.

part of error log:
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
core.js:6260 ERROR TypeError: Cannot read property 'category' of undefined
    at Function.addStepsFor (rate.ts:31)
    at products.selectors.ts:246
    at store.js:1061
    at memoized (store.js:976)
    at defaultStateFn (store.js:1016)
    at store.js:1070
    at memoized (store.js:976)
    at store.js:1015
    at Array.map (<anonymous>)
    at defaultStateFn (store.js:1011)
defaultErrorLogger @ core.js:6260
```

[error.log.txt](https://github.com/factoriolab/factorio-lab/files/4706369/error.log.txt)
[0.18.26_64px.zip](https://github.com/factoriolab/factorio-lab/files/4706372/0.18.26_64px.zip)

**Comment by dcbroad3** [comment]
Sure, I may not be able to check it for a couple days though. Could you create a new issue with this info?

**Comment by dcbroad3** [comment]
What I can tell you off the top of my head is that it's saying an object is undefined where the app expects an object with a category field. So it's not a missing category but a missing object, somehow.
