### ISSUE TITLE
Linear programming matrix calculations

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#90]
Will likely be essential to mod support to implement a true linear programming matrix solver rather than the existing uranium and oil utilities.

**Comment by bbarry** [comment]
perhaps https://github.com/IjzerenHein/kiwi.js/

**Comment by dcbroad3** [comment]
> perhaps https://github.com/IjzerenHein/kiwi.js/

@bbarry kiwi.js seems great, I've got it working doing simple matrix math for oil recipes. The only catch is that it uses the native JavaScript number, which will lose precision and the result won't be easy to represent as a true fraction. 

I think my approach is going to have to be: 
1. Get the calculator working with kiwi.js and approximate numbers
2. Fork/rewrite kiwi.js and replace numeric operations with this repo's Rational class

**Comment by hhrhhr** [comment]
Recently, I tried to load all Angel's mods into a Kirk calculator. The page with the wooden chest opened in about 20 minutes ...
Due to the huge amount of resources and products and the many relationships, matrix equations are too expensive to solve in JS. Will the method you propose be faster?

**Comment by dcbroad3** [comment]
> Due to the huge amount of resources and products and the many relationships, matrix equations are too expensive to solve in JS. Will the method you propose be faster?

That seems pretty extreme. The algorithm I've been looking into (kiwi.js uses cassowary) is different from the Kirk algorithm (simplex) but I'm not far enough yet to be able to make any observations about relative performance between the two. 

One thing I can say is that in Factorio Lab, if there is a direct recipe for an item, it does not use matrix calculations for that recipe. I _think_ Kirk's calculator does the same, though. So, for it to have made such a huge difference with Angel's, there would have to be a huge number of recipes that require matrix math. 

My approach has also already been that Factorio Lab will generate the smallest possible matrix for the given ingredients. So, if you don't include uranium products in your list, it won't include uranium recipes in the matrix. I doubt that would affect performance significantly, though. 

Lastly, I've realized that Factorio Lab likely needs a generic way to enable / disable recipes, which could help minimize the size of these matrices. This is effectively what the current "Oil Recipe" setting does, it says to ignore the other oil processing recipes, but a generic way to do that for all complex recipes would likely be helpful (for example, this could be a generic way to disable Kovarex enrichment process). That'd be a new issue though, it isn't covered by any existing ones.

**Comment by bbarry** [comment]
It should be possible to move the solver out into a web worker thread also to reduce the unresponsive time for calculations.
