### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#97]
Documentation on how to use the calculator and all its features.

**Comment by bbarry** [comment]
This sounds interesting. Are you thinking inline on the live site or markdown in a docs directory here?

**Comment by dcbroad3** [comment]
That is a good question and not something I've decided yet. Ideally I want the UI to be self-explanatory, but clearly that can't always be the case. I personally can't stand it when websites try to give you a guided tour, so I doubt I'd do that. I'd either try to have some 'help' option for different UI elements, or I'd build markdown docs in a directory here. At the moment I'm leaning towards the latter.
