### ISSUE TITLE
Improve sunburst usability

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#98]
* Try using icons and/or color coding on arcs in place of text
* Improve sunburst sizing based on screen width
* Experiment with alternate hierarchy formats like vertical stack

**Comment by proegssilb** [comment]
Should having an option to move the sunburst to the side on larger screens be part of this issue, or added to a different one?

**Comment by Shadowhenge** [comment]
So I would use a muted color palette.  Use red for raw materials, orange for 1st stage products like plates, yellow for 2nd stage products like copper coils.  Green for end products like green circuits, blue for end products that contain other products (like inserters), and purple for final stage products (science packs).  

I can design an aesthetic spectrum for you, I just need to to know what color space you are in.  If this is only for the web I can get you hex codes.  As for the icons I think you can extract that just as easy as I can.  If someone wants to paste a list of all items in the game In the code format you desire I can work on a color mapping.  there'll probably be 3 shades of each color so there is separation in the final chart.  I'm thinking logical gradients with some items being slightly different in the same category so if they are adjacent there is still a difference visually but I'll have to map out every possible production chain for each item to see how many variances are needed.

**Comment by dcbroad3** [comment]
> Should having an option to move the sunburst to the side on larger screens be part of this issue, or added to a different one?

@proegssilb By this you mean view the list and hierarchy simultaneously if screen width is large enough? This makes sense to me, and would probably still be part of this issue. I imagine the /hierarchy route would still exist and only show the sunburst, but the /list route might also show the diagram if there's enough room, probably with an option to turn that on/off. 

@Shadowhenge This is definitely exclusively for the web so hex codes are ideal. I'm not sure I understand what you're asking for in terms of the list of items. There is a list of items, recipes, and icons [here](https://github.com/factoriolab/factorio-lab/blob/master/src/assets/0.18/data.json), but I imagine that's not what you're asking for. 

> I'll have to map out every possible production chain for each item to see how many variances are needed.

This makes me think you have not played Factorio, I'm not sure whether this is really feasible 😅

**Comment by dcbroad3** [comment]
Another note @Shadowhenge, the next item to do on my list is to work on supporting mods, which means the list of items/recipes/icons should not be assumed to be static, so I would bear that in mind before attempting to design a solution.

**Comment by dcbroad3** [comment]
Just saw this on the Factorio subreddit:
https://www.reddit.com/r/factorio/comments/guinf4/average_colours_of_some_of_the_new_icons_for/
These would definitely be worth trying out in coloring the sunburst arcs.

**Comment by proegssilb** [comment]
[Try viewing this lab page on a tall browser window (mine is 1545x1298).](https://factoriolab.github.io/hierarchy#eJxlUFsOwyAMu02/qipOeBWpd6q2+0tjrFKGAx/YJsYh94WkXTpEZEcyh8lhdlgcVoftgdtrPNfHkmPuAXbmsJOVJqQom073TAdaeKOwpZGFC6BgJTQP5dYal5TMQmg+fK9yjOS1WeUZVU6BhDEa5wAxqCxB2R76u7T+HYkdQx1MFwZn2/vqfws6jw83w3co)

There's two approaches to balance out the space usage. One is to find a way to let the sunburst view float off to the right if your browser is wide enough, and let the list of items continue to be what it is. Maybe [this image](https://snipboard.io/TyHDaI.jpg) will help describe the effect? To use Bootstrap terms, you put the item selection list itself and the Sunburst as two columns in the same row, and decrease their column width on xl-wide devices, and then the item list and breadcrumbs would be in a second row.

The other approach would be to show the List View and Hierarchy Views side by side, with some styling sync between them to help the user not get lost in the list. Again using bootstrap terms, you leave the item selection in its own row, but then on xl screens, you hide the tabs used to switch between List and Hierarchy, and just show both tabs in two columns in a second row.

Either way, the specific issue that's happening on my screen is that with all 7 sciences and the sunburst view, there isn't a lot of vertical space left for the actual item list, and the information density is rather low. Making better use of the right-side of the screen would increase density by freeing up vertical space, and generally make it easier to use factoriolab in practice.

Does this help clear things up?

**Comment by dcbroad3** [comment]
> [Try viewing this lab page on a tall browser window (mine is 1545x1298).](https://factoriolab.github.io/hierarchy#eJxlUFsOwyAMu02/qipOeBWpd6q2+0tjrFKGAx/YJsYh94WkXTpEZEcyh8lhdlgcVoftgdtrPNfHkmPuAXbmsJOVJqQom073TAdaeKOwpZGFC6BgJTQP5dYal5TMQmg+fK9yjOS1WeUZVU6BhDEa5wAxqCxB2R76u7T+HYkdQx1MFwZn2/vqfws6jw83w3co)
> 
> There's two approaches to balance out the space usage. One is to find a way to let the sunburst view float off to the right if your browser is wide enough, and let the list of items continue to be what it is. Maybe [this image](https://snipboard.io/TyHDaI.jpg) will help describe the effect? To use Bootstrap terms, you put the item selection list itself and the Sunburst as two columns in the same row, and decrease their column width on xl-wide devices, and then the item list and breadcrumbs would be in a second row.
> 
> The other approach would be to show the List View and Hierarchy Views side by side, with some styling sync between them to help the user not get lost in the list. Again using bootstrap terms, you leave the item selection in its own row, but then on xl screens, you hide the tabs used to switch between List and Hierarchy, and just show both tabs in two columns in a second row.
> 
> Either way, the specific issue that's happening on my screen is that with all 7 sciences and the sunburst view, there isn't a lot of vertical space left for the actual item list, and the information density is rather low. Making better use of the right-side of the screen would increase density by freeing up vertical space, and generally make it easier to use factoriolab in practice.
> 
> Does this help clear things up?

I think so, thanks for the detailed writeup! I'm sure this will be an iterative process so I do have a staging environment where I can experiment before publishing to make sure I'm resolving the issues. I'll reach back out when I get to that point, no promises on timeline.

**Comment by dcbroad3** [comment]
Ultimately, the sunburst is just not the right diagram choice for Factorio recipe visualization. Sankey is more commonly used and is a better representation. Closing this issue in favor of a separate issue to add a Sankey to replace sunburst.
